### PR TITLE
Replace usage of commons collections 3 with commons collections 4

### PR DESCRIPTION
**Pull request by cziegeler**
Commons collections 3 is outdated and not maintained anymore, this change updates all usage to commons collections 4 - which is already used in some places

### CODE REVIEW

**Comment by kwin** [comment]
As long as it is provided by the uber-jar it will be tricky to prevent those imports from sneaking in again. Any reason why even https://repo1.maven.org/maven2/com/adobe/aem/uber-jar/6.5.21/uber-jar-6.5.21.jar still contains Collections 3? I would expect that to be only provided in https://repo1.maven.org/maven2/com/adobe/aem/uber-jar/6.5.21/uber-jar-6.5.21-apis-with-deprecations.jar....

**Comment by kwin** [comment]
Is there maybe some configuration on https://github.com/adobe/aemanalyser-maven-plugin/tree/main/aemanalyser-maven-plugin#configuration which could be leveraged to make the build fail in case of using deprecated API (is there even an analyser task for it)?

**Comment by cziegeler** [comment]
@kwin I agree that it would be nice to prevent reintroduction of usage of such APIs. The best place is a PR review - not fool proof of course.
The aemanalyser maven plugin checks such API usage and by default WARNs. It can be changed to fail.
(Site note: the reporting in the latest versions of the plugin is currently broken)

**Comment by cziegeler** [comment]
Is anything missing to apply this PR?

**Review by kwin — APPROVED** [review]

**Comment by cziegeler** [comment]
Can someone please merge this?

**Pull request merged**
