### PR TITLE
Added Icon Picker.

### PR DESCRIPTION
**Pull request by kooroshd**
I've added the icon picker widget to the project. However, when I try to run the build in my local AEM instance the build fails. Here is the error I get:

[ERROR] icon-picker.js:1:1:'ACS' has not been fully defined yet.
[ERROR] icon-picker.js:1:31:'CQ' has not been fully defined yet.
[ERROR] icon-picker.js:1:45:'CQ' has not been fully defined yet.
[ERROR] icon-picker.js:121:17:'CQ' has not been fully defined yet.
[ERROR] icon-picker.js:148:31:Expected '!==' and instead saw '!='.
[ERROR] icon-picker.js:164:22:Expected '===' and instead saw '=='.
[ERROR] icon-picker.js:164:36:Expected '{' and instead saw 'path'.
[ERROR] icon-picker.js:167:49:Expected '!==' and instead saw '!='.
[ERROR] icon-picker.js:169:29:Combine this with the previous 'var' statement.
[ERROR] icon-picker.js:170:25:eval is evil.
[ERROR] icon-picker.js:174:25:'CQ' is not defined.
[ERROR] icon-picker.js:182:20:'e' is already defined.
[ERROR] icon-picker.js:183:17:'CQ' is not defined.
[ERROR] icon-picker.js:188:22:Expected '===' and instead saw '=='.
[ERROR] icon-picker.js:188:36:Expected '{' and instead saw 'path'.
[ERROR] icon-picker.js:190:49:Expected '!==' and instead saw '!='.
[ERROR] icon-picker.js:192:25:eval is evil.
[ERROR] icon-picker.js:194:28:'e' is already defined.
[ERROR] icon-picker.js:195:25:'CQ' is not defined.
[ERROR] icon-picker.js:202:20:'e' is already defined.
[ERROR] icon-picker.js:203:17:'CQ' is not defined.
[ERROR] icon-picker.js:206:17:Combine this with the previous 'var' statement.
[ERROR] icon-picker.js:207:31:'ACS' is not defined.
[ERROR] icon-picker.js:269:26:Expected '!==' and instead saw '!='.
[ERROR] icon-picker.js:269:51:Expected '!==' and instead saw '!='.
[ERROR] icon-picker.js:269:62:Expected '{' and instead saw 'return'.
[ERROR] icon-picker.js:270:30:Expected '===' and instead saw '=='.
[ERROR] icon-picker.js:273:17:Combine this with the previous 'var' statement.
[ERROR] icon-picker.js:274:26:Expected '{' and instead saw 'return'.
[ERROR] icon-picker.js:275:26:Expected '{' and instead saw 'return'.
[ERROR] icon-picker.js:329:17:Combine this with the previous 'var' statement.
[ERROR] icon-picker.js:329:24:'CQ' is not defined.
[ERROR] icon-picker.js:329:32:Expected an identifier and instead saw 'eval' (a reserved word).
[ERROR] icon-picker.js:329:36:eval is evil.
[ERROR] icon-picker.js:332:21:Combine this with the previous 'var' statement.
[ERROR] icon-picker.js:333:21:Combine this with the previous 'var' statement.
[ERROR] icon-picker.js:334:21:Combine this with the previous 'var' statement.
[ERROR] icon-picker.js:334:32:'CQ' is not defined.
[ERROR] icon-picker.js:335:21:Combine this with the previous 'var' statement.
[ERROR] icon-picker.js:335:48:Expected '===' and instead saw '=='.
[ERROR] icon-picker.js:336:22:Move 'var' declarations to the top of the function.
[ERROR] icon-picker.js:336:22:Stopping.  (65% scanned).
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] ACS AEM Commons - Reactor Project ................. SUCCESS [0.134s]
[INFO] ACS AEM Commons Bundle ............................ SUCCESS [30.468s]
[INFO] ACS AEM Commons Twitter Support Bundle ............ SUCCESS [5.516s]
[INFO] ACS AEM Commons Package ........................... FAILURE [2.850s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 40.321s
[INFO] Finished at: Thu Jul 09 15:09:20 PDT 2015
[INFO] Final Memory: 69M/454M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.codehaus.mojo:jslint-maven-plugin:1.0.1:jslint (default) on project acs-aem-commons-content: Issues found in project. -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :acs-aem-commons-content

### CODE REVIEW

**Comment by justinedelson** [comment]
Thanks. Those are errors coming out of jshint because the JavaScript code doesn't match best practices. Most of these are easy enough to fix while merging. The only one which worries me is using eval and I assume based on a quick view of the code, this can't be easily refactored. So we may need to suppress the eval checking rule.

One question - how do you actually use this? :)  For some reason, when I saw Marc's tweet, I assume it was a plugin for the RTE, but it looks like it is a regular widget. Do you have a sample dialog.xml which uses it?

**Comment by koolrush** [comment]
It is a widget and not an RTE plugin. Although, plugin is something we've
been wanting to build so if someone builds it we'll be very interested in
it.

In order to use the icon picker in a dialog.xml add a field with
xtype="graphiciconselection" and the options attribute set to the path to
an ACS Commons general list that holds key value pairs for your Font
Awesome icons. Here is a snippet from a sample dialog:

<icon
jcr:primaryType="cq:Widget"
allowBlank="{Boolean}true"
fieldLabel="Icon"
fieldDescription=""
name="./icon"
value="fa-user"
options="/etc/acs-commons/lists/global-icons/_jcr_content.list.json"
xtype="graphiciconselection"/>

I've attached a sample general list.

Let me know if you need anything else.

**Comment by justinedelson** [comment]
This is merged and pushed. I also added a generic list with *all* font awesome icons, although I expect that most usages will actually use some subset.

**Comment by justinedelson** [comment]
In 892b33e5fc562f96271847c73c1d80976f28f830, I also added a TouchUI version of this widget.

**Pull request merged**
