### PR TITLE
#2704 - Fixed issue with MCP report generation throwing an exception,…

### PR DESCRIPTION
**Pull request by davidjgonzalez**
… and fixed some minor UI issues on AEM SDK (added BG color)

@joerghoh  can you take a look at this. I think some of the report refactoring introduced this regression.

One thing i found strange on my runs of Renovator, is the `@Inject`ion of the`rows` field never happens (or rather its always null) in GenericReport.java -- Is this expected? What's the point of that? Should we have a comment clarifying the strategy there (always null? conditionally null - if so what's the condition, etc.) .. it wasnt obvious to me why rows is null but rowsData isnt bull (which gets set to rows in the @PostConstruct)

Update: it appears this is still throwing an exception (sometimes?)

```
28.09.2021 13:09:49.577 *ERROR* [pool-40-thread-3] com.adobe.acs.commons.mcp.impl.ProcessInstanceImpl Error while performing JCR operations
java.lang.NullPointerException: null
	at com.adobe.acs.commons.mcp.model.GenericReport.persist(GenericReport.java:83)
	at com.adobe.acs.commons.mcp.impl.processes.renovator.Renovator.storeReport(Renovator.java:808)
	at com.adobe.acs.commons.mcp.impl.ProcessInstanceImpl.lambda$halt$16(ProcessInstanceImpl.java:342)
	at com.adobe.acs.commons.mcp.impl.ProcessInstanceImpl.asServiceUser(ProcessInstanceImpl.java:294)
	at com.adobe.acs.commons.mcp.impl.ProcessInstanceImpl.halt(ProcessInstanceImpl.java:340)
	at com.adobe.acs.commons.mcp.impl.ProcessInstanceImpl.runStep(ProcessInstanceImpl.java:217)
	at com.adobe.acs.commons.mcp.impl.ProcessInstanceImpl.lambda$runStep$13(ProcessInstanceImpl.java:234)
	at java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:891)
	at com.adobe.acs.commons.fam.impl.ActionManagerImpl.runCompletionTasks(ActionManagerImpl.java:291)
	at com.adobe.acs.commons.fam.impl.ActionManagerImpl.lambda$performAutomaticCleanup$6(ActionManagerImpl.java:321)
	at com.adobe.acs.commons.fam.impl.TimedRunnable.run(TimedRunnable.java:91)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

With this SNAPSHOP.

Thanks

### CODE REVIEW

**Review by badvision — APPROVED** [review]
Looks good, any chance we can restore the progress bars in the process list also?

**Comment by davidjgonzalez** [comment]
@badvision with this fix were still seeing

```
29.09.2021 13:35:25.228 *ERROR* [pool-43-thread-4] com.adobe.acs.commons.fam.impl.ActionManagerImpl Caught exception in task: Unable to create node at /var/audit/com.day.cq.wcm.core.page/content/wknd/language-masters/en/adventures-new/surf-camp-costa-rica
org.apache.sling.api.resource.PersistenceException: Unable to create node at /var/audit/com.day.cq.wcm.core.page/content/wknd/language-masters/en/adventures-new/surf-camp-costa-rica
	at org.apache.sling.jcr.resource.internal.helper.jcr.JcrResourceProvider.create(JcrResourceProvider.java:480) [org.apache.sling.jcr.resource:3.0.18]
	at org.apache.sling.resourceresolver.impl.providers.stateful.AuthenticatedResourceProvider.create(AuthenticatedResourceProvider.java:182) [org.apache.sling.resourceresolver:1.6.8]
	at org.apache.sling.resourceresolver.impl.helper.ResourceResolverControl.create(ResourceResolverControl.java:379) [org.apache.sling.resourceresolver:1.6.8]
	at org.apache.sling.resourceresolver.impl.helper.ResourceResolverControl.copy(ResourceResolverControl.java:572) [org.apache.sling.resourceresolver:1.6.8]
	at org.apache.sling.resourceresolver.impl.helper.ResourceResolverControl.move(ResourceResolverControl.java:621) [org.apache.sling.resourceresolver:1.6.8]
	at org.apache.sling.resourceresolver.impl.ResourceResolverImpl.move(ResourceResolverImpl.java:1102) [org.apache.sling.resourceresolver:1.6.8]
	at com.adobe.acs.commons.mcp.impl.processes.renovator.Renovator.moveAuditsForChildNodeCategories(Renovator.java:461)
	at com.adobe.acs.commons.mcp.impl.processes.renovator.Renovator.lambda$moveAuditsForChildNode$11(Renovator.java:445)
	at com.adobe.acs.commons.fam.impl.ActionManagerImpl.withResolver(ActionManagerImpl.java:200)
	at com.adobe.acs.commons.fam.impl.ActionManagerImpl.runActionAndLogErrors(ActionManagerImpl.java:167)
	at com.adobe.acs.commons.fam.impl.ActionManagerImpl.lambda$deferredWithResolver$0(ActionManagerImpl.java:159)
	at com.adobe.acs.commons.fam.impl.TimedRunnable.run(TimedRunnable.java:91)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: javax.jcr.ItemExistsException: surf-camp-costa-rica
	at org.apache.jackrabbit.oak.jcr.session.NodeImpl$5.perform(NodeImpl.java:290) [org.apache.jackrabbit.oak-jcr:1.10.8]
	at org.apache.jackrabbit.oak.jcr.session.NodeImpl$5.perform(NodeImpl.java:267) [org.apache.jackrabbit.oak-jcr:1.10.8]
	at org.apache.jackrabbit.oak.jcr.delegate.SessionDelegate.perform(SessionDelegate.java:207) [org.apache.jackrabbit.oak-jcr:1.10.8]
	at org.apache.jackrabbit.oak.jcr.session.ItemImpl.perform(ItemImpl.java:112) [org.apache.jackrabbit.oak-jcr:1.10.8]
	at org.apache.jackrabbit.oak.jcr.session.NodeImpl.addNode(NodeImpl.java:267) [org.apache.jackrabbit.oak-jcr:1.10.8]
	at org.apache.sling.jcr.resource.internal.helper.jcr.JcrResourceProvider.create(JcrResourceProvider.java:449) [org.apache.sling.jcr.resource:3.0.18]
	... 16 common frames omitted
```

Should we be checking if it exists, and if it does skip? or delete/replace? Or so some sort of merge of subnodes?

**Comment by badvision** [comment]
> @badvision with this fix were still seeing
> 
> ```
> 29.09.2021 13:35:25.228 *ERROR* [pool-43-thread-4] com.adobe.acs.commons.fam.impl.ActionManagerImpl Caught exception in task: Unable to create node at /var/audit/com.day.cq.wcm.core.page/content/wknd/language-masters/en/adventures-new/surf-camp-costa-rica
> org.apache.sling.api.resource.PersistenceException: Unable to create node at /var/audit/com.day.cq.wcm.core.page/content/wknd/language-masters/en/adventures-new/surf-camp-costa-rica
> 	at org.apache.sling.jcr.resource.internal.helper.jcr.JcrResourceProvider.create(JcrResourceProvider.java:480) [org.apache.sling.jcr.resource:3.0.18]
> 	at org.apache.sling.resourceresolver.impl.providers.stateful.AuthenticatedResourceProvider.create(AuthenticatedResourceProvider.java:182) [org.apache.sling.resourceresolver:1.6.8]
> 	at org.apache.sling.resourceresolver.impl.helper.ResourceResolverControl.create(ResourceResolverControl.java:379) [org.apache.sling.resourceresolver:1.6.8]
> 	at org.apache.sling.resourceresolver.impl.helper.ResourceResolverControl.copy(ResourceResolverControl.java:572) [org.apache.sling.resourceresolver:1.6.8]
> 	at org.apache.sling.resourceresolver.impl.helper.ResourceResolverControl.move(ResourceResolverControl.java:621) [org.apache.sling.resourceresolver:1.6.8]
> 	at org.apache.sling.resourceresolver.impl.ResourceResolverImpl.move(ResourceResolverImpl.java:1102) [org.apache.sling.resourceresolver:1.6.8]
> 	at com.adobe.acs.commons.mcp.impl.processes.renovator.Renovator.moveAuditsForChildNodeCategories(Renovator.java:461)
> 	at com.adobe.acs.commons.mcp.impl.processes.renovator.Renovator.lambda$moveAuditsForChildNode$11(Renovator.java:445)
> 	at com.adobe.acs.commons.fam.impl.ActionManagerImpl.withResolver(ActionManagerImpl.java:200)
> 	at com.adobe.acs.commons.fam.impl.ActionManagerImpl.runActionAndLogErrors(ActionManagerImpl.java:167)
> 	at com.adobe.acs.commons.fam.impl.ActionManagerImpl.lambda$deferredWithResolver$0(ActionManagerImpl.java:159)
> 	at com.adobe.acs.commons.fam.impl.TimedRunnable.run(TimedRunnable.java:91)
> 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
> 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
> 	at java.lang.Thread.run(Thread.java:748)
> Caused by: javax.jcr.ItemExistsException: surf-camp-costa-rica
> 	at org.apache.jackrabbit.oak.jcr.session.NodeImpl$5.perform(NodeImpl.java:290) [org.apache.jackrabbit.oak-jcr:1.10.8]
> 	at org.apache.jackrabbit.oak.jcr.session.NodeImpl$5.perform(NodeImpl.java:267) [org.apache.jackrabbit.oak-jcr:1.10.8]
> 	at org.apache.jackrabbit.oak.jcr.delegate.SessionDelegate.perform(SessionDelegate.java:207) [org.apache.jackrabbit.oak-jcr:1.10.8]
> 	at org.apache.jackrabbit.oak.jcr.session.ItemImpl.perform(ItemImpl.java:112) [org.apache.jackrabbit.oak-jcr:1.10.8]
> 	at org.apache.jackrabbit.oak.jcr.session.NodeImpl.addNode(NodeImpl.java:267) [org.apache.jackrabbit.oak-jcr:1.10.8]
> 	at org.apache.sling.jcr.resource.internal.helper.jcr.JcrResourceProvider.create(JcrResourceProvider.java:449) [org.apache.sling.jcr.resource:3.0.18]
> 	... 16 common frames omitted
> ```
> 
> Should we be checking if it exists, and if it does skip? or delete/replace? Or so some sort of merge of subnodes?

This error is nothing in the report generation.  Looking @ the stacktrace that's an error related to moving nodes in renovator.  We should move that to its own issue I think.

**Comment by davidjgonzalez** [comment]
Replaced by #2708

**Pull request closed without merging**
