### PR TITLE
adjust ACEs for acs-commons-package-replication-status-event-service …

### LINKED ISSUE #1327: Package which contains ACL entries can't be properly processed by the Package Replication Status Updater
## Required Information

* [ ] AEM Version, including Service Packs, Cumulative Fix Packs, etc: 6.3 SP2
* [ ] ACS AEM Commons Version: 3.14.12

### Expected Behavior

When activating the attached package, leveraging [Package Replication Status Updater](https://adobe-consulting-services.github.io/acs-aem-commons/features/package-replication-status-updater/index.html), the package should be successfully activated without errors in a log and also replication properties should be set on activated content in author.

### Actual Behavior

The package is activated and available in publish instance but activating the attached package, or any other, which contains ACL entries, an exception is thrown and replication properties are not set for the content that is being activated.

### Steps to Reproduce

1. Login as an _admin_ user in CRX via /crx/packmgr/index.jsp
2. Upload the package attached and try to activate it.
3. Check error.log for the errors => javax.jcr.AccessDeniedException: Access denied is thrown.

Note that package has AC Handling set to MERGE under the _Advanced tab_ in a _Edit package_ dialog.

`12.04.2018 13:55:18.069 *ERROR* [sling-threadpool-ccd8f959-e24b-4861-a8f8-e6173395f99e-(apache-sling-job-thread-pool)-11-<main queue>(acs-commons/replication/package)] org.apache.jackrabbit.vault.fs.impl.io.DocViewSAXImporter Error while applying access control content.
javax.jcr.AccessDeniedException: Access denied.
	at org.apache.jackrabbit.oak.spi.security.authorization.accesscontrol.AbstractAccessControlManager.checkPermissions(AbstractAccessControlManager.java:200)
	at org.apache.jackrabbit.oak.spi.security.authorization.accesscontrol.AbstractAccessControlManager.getTree(AbstractAccessControlManager.java:167)
	at org.apache.jackrabbit.oak.spi.security.authorization.cug.impl.CugAccessControlManager.getCugPolicy(CugAccessControlManager.java:239)
	at org.apache.jackrabbit.oak.spi.security.authorization.cug.impl.CugAccessControlManager.getPolicies(CugAccessControlManager.java:99)
	at org.apache.jackrabbit.oak.security.authorization.composite.CompositeAccessControlManager.getPolicies(CompositeAccessControlManager.java:78)
	at org.apache.jackrabbit.oak.jcr.delegate.AccessControlManagerDelegator$5.perform(AccessControlManagerDelegator.java:97)
	at org.apache.jackrabbit.oak.jcr.delegate.AccessControlManagerDelegator$5.perform(AccessControlManagerDelegator.java:93)
	at org.apache.jackrabbit.oak.jcr.delegate.SessionDelegate.perform(SessionDelegate.java:208)
	at org.apache.jackrabbit.oak.jcr.delegate.AccessControlManagerDelegator.getPolicies(AccessControlManagerDelegator.java:93)
	at org.apache.jackrabbit.oak.jcr.delegate.JackrabbitAccessControlManagerDelegator.getPolicies(JackrabbitAccessControlManagerDelegator.java:136)
	at org.apache.jackrabbit.vault.fs.impl.io.JackrabbitACLImporter$ImportedPolicy.getPolicy(JackrabbitACLImporter.java:192)
	at org.apache.jackrabbit.vault.fs.impl.io.JackrabbitACLImporter$ImportedAcList.apply(JackrabbitACLImporter.java:254)
	at org.apache.jackrabbit.vault.fs.impl.io.JackrabbitACLImporter.close(JackrabbitACLImporter.java:158)
	at org.apache.jackrabbit.vault.fs.impl.io.DocViewSAXImporter.endElement(DocViewSAXImporter.java:1154)
	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.endElement(AbstractSAXParser.java:609)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanEndElement(XMLDocumentFragmentScannerImpl.java:1782)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:2973)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:606)
	at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next(XMLNSDocumentScannerImpl.java:117)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:510)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:848)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:777)
	at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1213)
	at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:649)
	at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl.parse(SAXParserImpl.java:333)
	at org.apache.jackrabbit.vault.fs.impl.io.GenericArtifactHandler.accept(GenericArtifactHandler.java:99)
	at org.apache.jackrabbit.vault.fs.io.Importer.commit(Importer.java:896)
	at org.apache.jackrabbit.vault.fs.io.Importer.commit(Importer.java:801)
	at org.apache.jackrabbit.vault.fs.io.Importer.commit(Importer.java:841)
	at org.apache.jackrabbit.vault.fs.io.Importer.commit(Importer.java:841)
	at org.apache.jackrabbit.vault.fs.io.Importer.commit(Importer.java:841)
	at org.apache.jackrabbit.vault.fs.io.Importer.run(Importer.java:415)
	at org.apache.jackrabbit.vault.packaging.impl.ZipVaultPackage.extract(ZipVaultPackage.java:234)
	at org.apache.jackrabbit.vault.packaging.impl.JcrPackageImpl.extract(JcrPackageImpl.java:397)
	at org.apache.jackrabbit.vault.packaging.impl.JcrPackageImpl.extract(JcrPackageImpl.java:356)
	at org.apache.jackrabbit.vault.packaging.impl.JcrPackageImpl.extract(JcrPackageImpl.java:342)
	at com.adobe.acs.commons.packaging.impl.PackageHelperImpl.getContents(PackageHelperImpl.java:318)
	at com.adobe.acs.commons.replication.status.impl.JcrPackageReplicationStatusEventHandler.setReplicationStatus(JcrPackageReplicationStatusEventHandler.java:258)
	at com.adobe.acs.commons.replication.status.impl.JcrPackageReplicationStatusEventHandler.process(JcrPackageReplicationStatusEventHandler.java:240)`

### Links

[we-retail-test-failed.zip](https://github.com/Adobe-Consulting-Services/acs-aem-commons/files/1903472/we-retail-test-failed.zip)

@kwin fyi. Please add more info if needed.

### PR DESCRIPTION
**Pull request by justinedelson**
…service user to fix JcrPackageReplicationStatusEventHandler issue.

fixes #1327

Also adjust acHandling to merge to ensure that updated ACEs get reflected

### CODE REVIEW

**Comment by justinedelson** [comment]
@salexb @kwin please take a look at this change.

**Comment by kwin** [comment]
This seems to fix the issue, I am wondering though why jcr:modifyAccessControl is required as well. I would like though to enrich the exception handling as well. Therefore I proposed a different PR at https://github.com/Adobe-Consulting-Services/acs-aem-commons/pull/1329.

**Comment by salexb** [comment]
Fixes the issue for me as well, tnx, however agree with @kwin .

**Comment by justinedelson** [comment]
closing in favor of #1329

**Pull request closed without merging**
