### PR TITLE
using sling constants

### PR DESCRIPTION
**Pull request by heervisscher**

### CODE REVIEW

**Comment by heervisscher** [comment]
@badvision I think this is better with the right branch

**Comment by badvision** [comment]
Yes I think you're right.  I might just abandon the osgi 7 branch.  Thoughts?

**Comment by heervisscher** [comment]
I would leave it..., just merge in these changes

**Comment by davidjgonzalez** [comment]
Closing to clean-up PR backlog, to help focus on v4.0.0 release. 

Non-4.0.0 release blocking PR's will not be merged until 4.0.0 release anyhow.

We can re-open post 4.0.0 release.

**Comment by davidjgonzalez** [comment]
Closing as we reverted back to SCR annotations: https://github.com/Adobe-Consulting-Services/acs-aem-commons/issues/1741#issuecomment-461836942

**Pull request closed without merging**
