### PR TITLE
#986: Rewrote UI for Generic lists to use Touch UI with backwards compatibility

### PR DESCRIPTION
**Pull request by badvision**
Also made an improvement to the MCP generated dialog code to support interface-based models

### CODE REVIEW

**Comment by badvision** [comment]
@adamcin any idea why I'm getting so many errors?

**Comment by badvision** [comment]
Confirmed that the build issues were caused by the changes in nodetypes.cnd.  Thanks @adamcin for the quick response to point me in the right direction. 😄

**Comment by badvision** [comment]
@kaushalmall this PR is ready for review.

**Comment by synox** [comment]
I am not ably to `move` a list. 

> Resource at '/mnt/overlay/acs-commons/components/utilities/generic-list-console/movepagewizard.html/etc/acs-commons/lists/test' not found: No resource found
> Cannot serve request to /mnt/overlay/acs-commons/components/utilities/generic-list-console/movepagewizard.html/etc/acs-commons/lists/test in /libs/sling/servlet/errorhandler/404.jsp

**Comment by badvision** [comment]
I must have left that button there kind of inadvertently.  @davidjgonzalez, @justinedelson should I get the move button working or should I just remove that option?  Thanks for reviewing @synox !

**Comment by badvision** [comment]
@synox Fixed that button just for you buddy! 😄

**Pull request merged**
