### PR TITLE
Feature/queryautocompletelist

### PR DESCRIPTION
**Pull request by kaushalmall**
Query autocomplete datasoruce.

  A datasource that takes a list of predicates and a display property to build out the autocomplete list.
  The path of the resource is saved in the JCR and the display property is used for better UX.

```
  /**
   * The predicate map.
   */
  - predicates (String[]) = type=cq:Page,path=/content/geometrixx,property=jcr:content/sling:resourceType,property.value=geometrixx/components/homepage

   /**
   * The display property name.
   */
   -displayProperty (String) = jcr:content/jcr:title.
```

### CODE REVIEW

**Comment by kaushalmall** [comment]
## Purpose

Query autocomplete datasource lets you build your [autocomplete](https://docs.adobe.com/docs/en/aem/6-1/ref/granite-ui/api/jcr_root/libs/granite/ui/components/foundation/form/autocomplete/index.html) list using an XPath query.

## How to Use

Setup your component dialog and the [autocomplete](https://docs.adobe.com/docs/en/aem/6-1/ref/granite-ui/api/jcr_root/libs/granite/ui/components/foundation/form/autocomplete/index.html) widget described in the documentation here.
* Add a "predicates" String array property to the autocomplete widget node
* Add a "displayProperty" String property to the autocomplete widget node
* Add a "datasource" node to the autocomplete widget node.
* Add an "options" node to the autocomplete widget node.

```
<autocomplete
        jcr:primaryType="nt:unstructured"
        sling:resourceType="granite/ui/components/foundation/form/autocomplete"
        fieldLabel="Autcomplete"
        name="./autocomplete"
        displayProperty="jcr:content/jcr:title"
        predicates="[type=cq:Page,path=/content/geometrixx,property=jcr:content/sling:resourceType,property.value=geometrixx/components/homepage]">
        <datasource
                jcr:primaryType="nt:unstructured"
                sling:resourceType="acs-commons/granite/ui/components/form/queryautocomplete/datasource" />
        <options
                jcr:primaryType="nt:unstructured"
                sling:resourceType="granite/ui/components/foundation/form/autocomplete/list" />
       </autocomplete>
```

### Example Dialog

In the example below, the "Autocomplete" node will show results of the query generated by the xpath query

`/jcr:root/content/geometrixx//element(*, cq:Page) [jcr:content/@sling:resourceType = 'geometrixx/components/homepage']`
The query is generated from using the predicate map

```
type=cq:Page
path=/content/geometrixx
property=jcr:content/sling:resourceType
property.value=geometrixx/components/homepage
```

which is defined by the "predicates" property on the widget node.

```
<?xml version="1.0" encoding="UTF-8"?>
   <jcr:root xmlns:jcr="http://www.jcp.org/jcr/1.0" xmlns:cq="http://www.day.com/jcr/cq/1.0" xmlns:nt="http://www.jcp.org/jcr/nt/1.0" xmlns:sling="http://sling.apache.org/jcr/sling/1.0" jcr:primaryType="nt:unstructured" jcr:title="List" sling:resourceType="cq/gui/components/authoring/dialog" helpPath="en/cq/current/wcm/default_components.html#List">
      <content
      		jcr:primaryType="nt:unstructured"
      		sling:resourceType="granite/ui/components/foundation/container">
         	<layout
         		jcr:primaryType="nt:unstructured"
         		sling:resourceType="granite/ui/components/foundation/layouts/fixedcolumns" margin="{Boolean}false" />
         	<items
         		jcr:primaryType="nt:unstructured">
            	<column
            		jcr:primaryType="nt:unstructured"
            		sling:resourceType="granite/ui/components/foundation/container">
               	<items
               		jcr:primaryType="nt:unstructured">
                  		<autocomplete
                  			jcr:primaryType="nt:unstructured"
                  			sling:resourceType="granite/ui/components/foundation/form/autocomplete"
                  			fieldLabel="Autcomplete"
                  			name="./autocomplete"
                  			displayProperty="jcr:content/jcr:title"
                  			predicates="[type=cq:Page,path=/content/geometrixx,property=jcr:content/sling:resourceType,property.value=geometrixx/components/homepage]">
                     		<datasource
                     			jcr:primaryType="nt:unstructured"
                     			sling:resourceType="acs-commons/granite/ui/components/form/queryautocomplete/datasource" />
                     		<options
                     			jcr:primaryType="nt:unstructured"
                     			sling:resourceType="granite/ui/components/foundation/form/autocomplete/list" />
                  </autocomplete>
               </items>
            </column>
         </items>
      </content>
   </jcr:root>
```

**Comment by kaushalmall** [comment]
@schoudry I added some documentation that might be helpful for you.

**Comment by kaushalmall** [comment]
I am guessing we will close this with #711 ?

**Comment by davidjgonzalez** [comment]
@kaushalmall @schoudry are this an #711 fundamentally the same? Do we need both? If not, which do you guys like better?

**Comment by kaushalmall** [comment]
I think Justin we can pull both as long they were consistent and Sreekanth made changes to make 711 like this one.

**Pull request merged**
