### PR TITLE
#3235 Add an option to ignore selectors in the url.

### PR DESCRIPTION
**Pull request by YegorKozlov**
#3235 Add an option to ignore selectors in the url.

### CODE REVIEW

**Comment by thcharan** [comment]
Looks good!

**Comment by thcharan** [comment]
@davidjgonzalez  - can this be part of upcoming release?
this helps quite a lot for implementations that relies quite heavily on url 'selectors'

**Review by davidjgonzalez — APPROVED** [review]

**Comment by davidjgonzalez** [comment]
@thcharan its in 6.4.0 which is just was released! Thanks!

**Comment by thcharan** [comment]
@davidjgonzalez  @YegorKozlov  - Great. Thank You.

**Pull request merged**
