### PR TITLE
Feature/aem remote assets

### PR DESCRIPTION
**Pull request by HitmanInWis**
Internal PR to do some cleanups before submitting to the main repo

### CODE REVIEW

**Comment by HitmanInWis** [comment]
sorry - haha meant to do this on the HS2 repo first...this will be coming later...

**Comment by justinedelson** [comment]
image

**Comment by HitmanInWis** [comment]
hahaha sorry I was hoping i could actually DELETE this PR ... wasnt planning on submitting this until just before SUMMIT AEM Rockstar

**Comment by justinedelson** [comment]
I believe if you delete the branch on your fork, the PR will disappear, but I'm not entirely sure.

**Pull request closed without merging**
