### PR TITLE
make Package Garbage Collection Scheduler AEMaaCS compatible

### PR DESCRIPTION
**Pull request by Polleke007**

### CODE REVIEW

**Review by davidjgonzalez — APPROVED** [review]

**Comment by Polleke007** [comment]
@davidjgonzalez can you approve the PR?

**Comment by davidjgonzalez** [comment]
@koenkicken it is failing due to missing CHANGELOG entry - can you add and then we can merge?

**Comment by koenkicken** [comment]
@davidjgonzalez CHANGELOG updated

**Comment by jfmitchell** [comment]
@Polleke007 out of interest - what’s the use case for cloud service? You should update the documentation to reflect this change, and the purpose.

**Pull request merged**
