### PR TITLE
Make last suffix (filename) pattern configurable

### PR DESCRIPTION
**Pull request by m-kay**
Fix: #575

### CODE REVIEW

**Comment by bstopp** [comment]
Maybe i'm not seeing the whole situation here. Wouldn't this require a significant number of configurations to support, since every image has a unique file name? 

That being true, then regex for the filename matcher should be a list of strings, instead of a single regex, since this class isn't a factory. But event then, now every time a new asset is uploaded you'd need to update the rules for this configuration to support that pattern.

Finally, the URL already has the file name in it, it's the resource name on which the *transform* extension is applied, does not duplication of tokens degrade the SEO performance? 

Just my thoughts.

**Comment by m-kay** [comment]
To support all filenames I would use a regex like .*?\.(jpg|jpeg|png|gif) or even .*
I don't understand this suffix check at all and I think in my case I don't need it, but to still support it I recommended to make it configurable instead of remove it completely.

The search engines are not aware of this Sling suffix so they suppose this suffix as the real file name and not the one included in the path. Furthermore if someone saves one of these images the filename is always image.jpg instead of the real filename because the browser isn't aware of this suffix either.

**Comment by davidjgonzalez** [comment]
Seems reasonable to me! Thanks!

**Comment by m-kay** [comment]
Thank you for merging. 
When will you release the next version? We would like to include this fix as soon as possible.

**Comment by davidjgonzalez** [comment]
@m-kay this is in 2.1.2; should be hitting adobe repo tomorrow (11/16)

**Pull request merged**
