### PR TITLE
bugfixes - 647 - node multifield panel

### PR DESCRIPTION
**Pull request by schoudry**
1) xtype selection doesnt work (values not saved) in node multifield
2) loadcontent event not fired on items in node multifield

### CODE REVIEW

**Comment by justinedelson** [comment]
@schoudry does this fix #647?

**Comment by schoudry** [comment]
yes

**Comment by justinedelson** [comment]
great. in the future, can you put "fixes #<issuenumber>" somewhere in the commit comment? then it automatically marks the corresponding issue as fixed when the PR is merged.

**Comment by schoudry** [comment]
@justinedelson sure, actually it was a mistake - i remember putting in comment relates the commit to bug

**Pull request merged**
