### PR TITLE
Independent configurations for PageRootProvider (Compat/6.0)

### PR DESCRIPTION
**Pull request by daniel-lima**
It corresponds to #1087 for AEM 6.0 and 6.1.

### CODE REVIEW

**Comment by HitmanInWis** [comment]
@justinedelson @davidjgonzalez 

QA'd this PR merged into latest compat/6.0 branch on AEM 6.1
- Tested with a fully functional demo site that depends on Page Root Provider
- Tested an existing Page Root Provider config (now deprecated)
- Tested deploying multiple Page Root Providers the new way
- Tested mixing new Page Root Providers with the deprecated config
- Tested adding/editing/removing Page Root Providers via Felix console

Everything works as expected.

In my opinion this is good to be merged.

**Comment by davidjgonzalez** [comment]
@daniel-lima and @HitmanInWis - LGTM but can you do a quick change to make LOG -> log per the proj guidelines? Otherwise we can merge!

**Comment by daniel-lima** [comment]
@davidjgonzalez , should we just rename "LOG" to "log"? Or should we replace

`private static final Logger LOG = LoggerFactory.getLogger(PageRootProviderMultiImpl.class);`

with

`private final Logger log = LoggerFactory.getLogger(getClass());`

Thanks!

**Comment by davidjgonzalez** [comment]
The former is fine; most loggers in the proj are static.

**Comment by daniel-lima** [comment]
@davidjgonzalez: done. Thanks!

**Comment by daniel-lima** [comment]
@HitmanInWis , thank you for your effort reviewing and QA'ing everything!

**Pull request merged**
