### PR TITLE
Added wcmuse support to handle multi field panel values

### PR DESCRIPTION
**Pull request by murilodag**
Could not create branch feature/multi-field-panel-wcmuse-support. Could you please create it and redirect the PR?

### CODE REVIEW

**Comment by justinedelson** [comment]
@murilodag not sure I understand what you mean about the branch. It seems like this should be merged to master and feature/6.2-compatibility. Is there a reason we should create a separate branch (and what would happen to that branch)?

**Comment by murilodag** [comment]
@justinedelson , I read in some contributing guide for this repository to merge new features to a feature/new-feature-name. I think it would be fine going master and feature/6.2-compatibility.

**Comment by justinedelson** [comment]
@murilodag that is referring to a branch in your fork.

**Comment by murilodag** [comment]
@justinedelson Thank you. Cancelling this PR to open a new correct one.

**Comment by justinedelson** [comment]
oh you don't need to do that.

**Comment by justinedelson** [comment]
but in the future, it makes things easier for you to manage.

**Pull request merged**
