### PR TITLE
Require Java 11 for building

### LINKED ISSUE #3108: Require Java 11 for building
Multiple test libraries require Java 11 these days:

- AEM Mocks since version 5.2.0
- Mockito since version 5.0

We should require Java 11 for building acs-aem-commons. That also allows to get rid of animalsniffer-maven-plugin and leverage `maven.compiler.release` instead of `maven.compiler.source` and `maven.compiler.target`. The minimum Java version should be enforced.

For now we can still build for Java 8 (even JDK 17 can still emit bytecode compatible with Java 8)

### PR DESCRIPTION
**Pull request by kwin**
This closes #3108

### CODE REVIEW

**Comment by kwin** [comment]
In order to still execute UTs/ITs with Java 8, Maven Toolchains should be used together with m-surefire-p/m-failsafe-p.

**Comment by davidjgonzalez** [comment]
@kwin  is this ready for review/merge?

**Comment by kwin** [comment]
Currently it will drop testing (i.e. run ITs) with Java 8 but I don't think this is really required...
Testing with Java 8 requires more tweaking on the GitHub Actions.

**Comment by kwin** [comment]
@davidjgonzalez This should be the last missing piece for also bringing the failing JDK8 back to green (as that was using the implicitly activated `java8` profile which lead to the `cloud` profile no longer being active implicitly).

**Review by davidjgonzalez — APPROVED** [review]

**Pull request merged**
