### PR TITLE
Fix edit dialog for system notifications (partial fix for #1839)

### PR DESCRIPTION
**Pull request by joerghoh**

### CODE REVIEW

**Comment by joerghoh** [comment]
@davidjgonzalez please approve :-)

**Comment by davidjgonzalez** [comment]
@joerghoh This PR has a bunch of unrelated commits in it. I thought I already approved the System Notifications fixes .. i'm confused as to what happened w this PR.

**Comment by joerghoh** [comment]
@davidjgonzalez ehm ... you are right! Looks like I haven't payed that much attention to it (or some rebase/merge to trunk failed). I guess I will raise a new PR.

**Comment by davidjgonzalez** [comment]
np - Ping or assign to me when the new PR is raised and ill check it out. Closing this PR.

**Comment by joerghoh** [comment]
See #1877 to my 2nd attempt

**Pull request closed without merging**
