### PR TITLE
HttpCache - Prep for 4.x release (Removes Combined* support for 4.0.0)

### PR DESCRIPTION
**Pull request by davidjgonzalez**
HttpCache was rather dirty, and some of the new additions were a bit overwrought This works well now, though it suppresses (removes the OSGi annotations) for the 2 new Combined features as they don't appear to work (and the logic looks strange -> wrong to me anyhow).
This also removes a number of the KeyValueCacheKey's files by reorganizing the logic.

### CODE REVIEW

**Comment by davidjgonzalez** [comment]
@niekraaijmakers FYI - The Combined* is disabled but in code (impl) still - youll want to revisit this later - though i think we may want to think through how these work.

**Comment by davidjgonzalez** [comment]
Will try to fix failing tests before work tomorrow

**Comment by niekraaijmakers** [comment]
Il will make some time to look into this today

**Comment by davidjgonzalez** [comment]
Updated metatype and hints..

image

Updated "key/value" derived extension osgi config definition

[image](https://user-images.githubusercontent.com/1451868/52570256-f225d280-2de0-11e9-8fd0-503c3ab92302.png)

**Comment by davidjgonzalez** [comment]
Looks like MCP tests are failing due to sftp host resolution? This sounds familiar?

**Comment by justinedelson** [comment]
@davidjgonzalez the reason the travis build is failing is this:

```
java.lang.Exception: Could not identify pid for OSGI-INF/metatype/com.adobe.acs.commons.httpcache.store.caffeine.impl.Config.xml
	at com.adobe.acs.commons.it.build.ScrMetadataIT.parseMetatype(ScrMetadataIT.java:267)
	at com.adobe.acs.commons.it.build.ScrMetadataIT.parseJar(ScrMetadataIT.java:185)
	at com.adobe.acs.commons.it.build.ScrMetadataIT.getDescriptorsFromCurrent(ScrMetadataIT.java:174)
	at com.adobe.acs.commons.it.build.ScrMetadataIT.test(ScrMetadataIT.java:98)
```

What this means is that `com.adobe.acs.commons.httpcache.store.caffeine.impl.Config` is now a configuration metatype which is not linked to any component (yeah, this could be more intuitive).

So removing this annotation class should fix the problem.

Can you go ahead and remove that class?

**Comment by davidjgonzalez** [comment]
@justinedelson ah - thanks - pushed fix.

**Comment by justinedelson** [comment]
ok. now it is failing because you changed some properties:

```
Property jmx.objectname on component com.adobe.acs.commons.httpcache.engine.impl.HttpCacheEngineImpl has different values (was: {com.adobe.acs.httpcache:type=HTTP Cache Engine}, is: {com.adobe.acs.commons.httpcache:type=HTTP Cache - Engine})
Property jmx.objectname on component com.adobe.acs.commons.httpcache.store.jcr.impl.JCRHttpCacheStoreImpl has different values (was: {com.adobe.acs.httpcache:type=JCR HTTP Cache Store}, is: {com.adobe.acs.commons.httpcache:type=HTTP Cache - JCR Cache Store})
Property jmx.objectname on component com.adobe.acs.commons.httpcache.store.mem.impl.MemHttpCacheStoreImpl has different values (was: {com.adobe.acs.httpcache:type=In Memory HTTP Cache Store}, is: {com.adobe.acs.commons.httpcache:type=HTTP Cache - In-Memory Cache Store}}
```

Are these necessary? (conceptually these are API changes)

**Comment by davidjgonzalez** [comment]
@justinedelson yeh - i figured since its 4.x it would good to correct them; we can revert them if we want (the prior prefix was nonsensical: `com.adobe.acs.httpcache` ) 

I dont think many ppl hook MBeans up to anything so the impact would be low? (though we would need to document on the 4.x.x page)

**Pull request merged**
