### PR TITLE
Prevent ISE when calling getBufferedString

### LINKED ISSUE #1848: AEM Environment Indicator breaks 6.5 interface
* [ ] AEM Version: `6.5`
* [ ] ACS AEM Commons Version: `4.0.1-SNAPSHOT`
* [ ] Reproducible on Latest? yes

### Expected Behavior

[AEM Environment Indicator](https://adobe-consulting-services.github.io/acs-aem-commons/features/environment-indicator/index..html) does not break anything when configured with any data.

### Actual Behavior

[How to Use](https://adobe-consulting-services.github.io/acs-aem-commons/features/environment-indicator/index..html#how-to-use) example breaks the instance interface:

crxdelite

start

### Steps to Reproduce

Implement the indicator just as described in [How to Use](https://adobe-consulting-services.github.io/acs-aem-commons/features/environment-indicator/index..html#how-to-use).

### PR DESCRIPTION
**Pull request by kwin**
Add guard to check if we really act on a writer-type response.

This fixes #1848

### CODE REVIEW

**Comment by kwin** [comment]
@badvision As this regression was never released I don't think we need to extend the changelog, right?

**Comment by badvision** [comment]
Yeah that's fine.  Thanks @kwin ! 👍

**Comment by davidjgonzalez** [comment]
@kwin are there any other effected features that need similar treatment? Iirc the buffered response was used elsewhere.

**Comment by kwin** [comment]
@davidjgonzalez Indeed there are some other places which need guards, I opened #1853 to treat those.

**Pull request merged**
