### PR TITLE
 Removed DynamicDeck dependency on deprecated package com.day.cq.dam.api.collection which causes problems w/ AEM CS deployments.

### PR DESCRIPTION
**Pull request by davidjgonzalez**
Reopening after false-merge/revert

### CODE REVIEW

**Comment by badvision** [comment]
Any chance we can get some test coverage for this module?

**Comment by davidjgonzalez** [comment]
adding @jasiwal - any info on test coverage timing? we fast-tracked the merge of this with the understanding there would be test coverage imminently.

**Comment by badvision** [comment]
Right now it's a blocker for AEMaaCS deployment so we need test coverage to understand if @davidjgonzalez's fix will not disrupt the functionality of the module.

**Comment by davidjgonzalez** [comment]
out of band, JB verified this patch does not break functionality.

**Comment by davidjgonzalez** [comment]
This had a bug with the call to `queryBuilder.loadQuery(..)` which is now fixed/verified

**Comment by badvision** [comment]
@jasiwal Any updates on test coverage?  It's not my favorite metric in the world but we should improve it a little before accepting this PR.

**Pull request merged**
