### PR TITLE
Bugfix #1780 - XSSFunctions API change broke XSS Taglib and JSPs using the Taglib 

### PR DESCRIPTION
**Pull request by josephrignanese**
Fix for #1780

### CODE REVIEW

**Comment by josephrignanese** [comment]
For now I have tried to minimise the changes made.
It may be simpler to remove the use of the xss taglib altogether and then use the xssAPI object directly.
Given the granite one is deprecated I've opted for the sling one where I had to make changes, but there are further references to the granite one in some of the other JSPs.

**Comment by josephrignanese** [comment]
Will update this with suggestions from comments on #1780 today.

**Comment by josephrignanese** [comment]
@davidjgonzalez going to need your advise on the travis failures

**Comment by davidjgonzalez** [comment]
@josephrignanese Should be easy enough - You just need update com.adobe.acs.commons.xss's `package-info.java` the version to 4.1.0.

Thanks for tackling this!

**Comment by josephrignanese** [comment]
@davidjgonzalez that last commit seemed to trigger a bunch of test failures in travis. Any idea what might be happening there?

**Comment by josephrignanese** [comment]
Helps if I look at the full log 👍. The expected exceptions from tests + where the travis web interface decided the log was too long to display through me off.

Anyway, turns out I missed an integration test - that's fixed now and build is passing.

**Pull request merged**
