### PR TITLE
Feature/2232 - Removes META-INF/vault files in SCM; Minor sonarqube fixes

### PR DESCRIPTION
**Pull request by davidjgonzalez**
* Removes the old properties.txt and friends (cnd, etc.) from SCM.
* Fixed a few CM related quality gate checks to allow it to pass/deploy to CM.

### CODE REVIEW

**Comment by justinedelson** [comment]
@davidjgonzalez this is a good idea. have you done a comparison between the generated META-INF/vault/* files between the last release and with these changes? If not, I'll try to script that and post the results here.

**Comment by davidjgonzalez** [comment]
@justinedelson adding the generated files for ui.apps and ui.content

here's the ui.apps properties.txt for a quick look

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE properties SYSTEM "http://java.sun.com/dtd/properties.dtd">
<properties>
<comment>ACS AEM Commons UI.Apps Package</comment>
<entry key="acHandling">merge</entry>
<entry key="created">2020-03-25T11:31:00.424-0400</entry>
<entry key="groupId">com.adobe.acs</entry>
<entry key="description">ACS AEM Commons content package containing code (/apps).</entry>
<entry key="version">4.4.3-SNAPSHOT</entry>
<entry key="requiresRoot">false</entry>
<entry key="dependencies">day/cq60/product:cq-content:6.3.64</entry>
<entry key="path">/etc/packages/adobe/consulting/acs-aem-commons-ui.apps.zip</entry>
<entry key="createdBy">davidg</entry>
<entry key="name">acs-aem-commons-ui.apps</entry>
<entry key="artifactId">acs-aem-commons-ui.apps</entry>
<entry key="group">adobe/consulting</entry>
</properties>
```

[ui.apps.meta-inf-vault.zip](https://github.com/Adobe-Consulting-Services/acs-aem-commons/files/4381790/ui.apps.meta-inf-vault.zip)

[ui.content.meta-inf-vault.zip](https://github.com/Adobe-Consulting-Services/acs-aem-commons/files/4381794/ui.content.meta-inf-vault.zip)

**Comment by justinedelson** [comment]
side by side diff: https://gist.github.com/justinedelson/8392242adf39ef7e746bf273e4a5df98

**Comment by davidjgonzalez** [comment]
base don the diff, looks like a benign change but keeps the code repo a little cleaner.

Am planning on cutting a release for @wimsymons since we've been putting him off for too long, and didnt want to get us caught w/ that possible properties.txt issue.

**Comment by kwin** [comment]
I think this breaks oakpal. I now get errors like 
```
[INFO] --- oakpal-maven-plugin:1.5.1:scan (oakpal-scan) @ acs-aem-commons-ui.apps ---
[INFO] Found a new index node [reference]. Reindexing is requested
[INFO] Reindexing will be performed for following indexes: [/oak:index/uuid, /oak:index/reference, /oak:index/nodetype]
[INFO] Indexing report
    - /oak:index/uuid*(0)
    - /oak:index/reference*(0)
    - /oak:index/nodetype*(1258)

[INFO] Reindexing completed
[INFO] Reindexing will be performed for following indexes: [/oak:index/principalName, /oak:index/authorizableId, /oak:index/acPrincipalName, /oak:index/repMembers]
[INFO] Indexing report
    - /oak:index/principalName*(2)
    - /oak:index/authorizableId*(2)
    - /oak:index/acPrincipalName*(0)
    - /oak:index/repMembers*(0)

[INFO] Reindexing completed
[ERROR] Error during processing of /apps/acs-commons/touchui-widgets/icon-picker: javax.jcr.nodetype.NoSuchNodeTypeException: Node type cq:ClientLibraryFolder does not exist
[ERROR] E /apps/acs-commons/touchui-widgets/icon-picker (javax.jcr.nodetype.NoSuchNodeTypeException: Node type cq:ClientLibraryFolder does not exist)
```

That is an issue though in oakpal which should be fixed there, as we shouldn't include any irrelevant metadata in packages (like the cnd for nodetypes which are always existing already).

**Comment by adamcin** [comment]
@kwin Sorry for just now seeing your question, as it looks like this issue has already been resolved. There are a couple ways to provide the platform CNDs to oakpal other than maintaining redundant CNDs in the package artifacts. One way is to use the [`cndNames`](http://adamcin.net/oakpal/oakpal-maven-plugin/scan-mojo.html#cndNames) parameter to reference specific CND resources on the test classpath. Another is to enable resolution by detecting `Sling-Nodetypes` manifest headers in test-scope dependencies. This enabled by setting [`slingNodeTypes`](http://adamcin.net/oakpal/oakpal-maven-plugin/scan-mojo.html#slingNodeTypes) to `true`. This option might be more convenient in the future now that Adobe's uber-jars (starting with 6.5.0) include the platform nodetypes. Finally, it is also possible to serialize the nodetypes into the `jcrNodetypes` json property of plans and checklists, but this method makes it harder to manually maintain those files if we are talking about the full set of aem nodetypes, rather than just nodetypes directly referenced by progress check implementations or forcedRoot primary/mixin types.

**Pull request merged**
