### PR TITLE
Feature/renovator audit trails

### LINKED ISSUE #2536: Renovator should handle updating audit log entries, as is the case when assets/pages are moved through the standard UI tooling
## Required Information

* [ ] AEM Version, including Service Packs, Cumulative Fix Packs, etc: 6.5.6
* [ ] ACS AEM Commons Version: *
* [ ] Reproducible on Latest? yes

### Behavior

When moving a set of assets using renovator, the audit trail nodes under /var/audit remain the original location and are thus disassociated from the asset. Compare this to what happens when you move an asset with the OOTB ui tooling, where the audit entires get moved and a new audit entry is added indicating the move took place.

### Steps to Reproduce

run renovator on some assets that have audit entries. Note that they are not moved.

### Note

Planning to submit a PR for this, just creating an issue to track it and as a reminder for myself to come back to it, and to give @badvision a chance to provide any thoughts he has incase there is reason that renovator shouldn't handle this.

### PR DESCRIPTION
**Pull request by shsteimer**
fixes #2536

### CODE REVIEW

**Comment by shsteimer** [comment]
I still need to add unit tests, but opening as a draft PR now to get code coverage and code climate feedback.

**Comment by shsteimer** [comment]
Is there a way to kick Travis to force a rebuild? The test that failed `RedirectFilterTest.testInvalidateOnChange` isn't something I touched, so thinking it might just be a flaky test.

**Comment by badvision** [comment]
There used to be an option to restart travis builds but it stopped showing up for me a couple of years ago.  Did you remember to update the changelog already, by chance?

**Comment by kwin** [comment]
Once you login at https://travis-ci.org/github/Adobe-Consulting-Services/acs-aem-commons/builds/763148871 there should be a button.

Screenshot 2021-03-16 at 20 15 36

**Review by badvision — APPROVED** [review]
Rock and roll!

**Pull request merged**
