### PR TITLE
update aws-sdk to the latest version

### PR DESCRIPTION
**Pull request by joerghoh**

### CODE REVIEW

**Comment by justinedelson** [comment]
Not sure this is a good idea -- the latest S3 connector appears to use 1.11.700: https://repo.adobe.com/nexus/content/groups/public/com/adobe/granite/com.adobe.granite.oak.s3connector/1.10.10/com.adobe.granite.oak.s3connector-1.10.10.pom

**Comment by joerghoh** [comment]
ok, what is the issue with the newer version of the aws-sdk?

**Comment by kwin** [comment]
`aws-sdk` is not embedded but an optional import. Depending on a newer version will make it never resolve with any AEM bundle. Compare also with https://github.com/Adobe-Consulting-Services/acs-aem-commons/pull/2422/files#diff-600376dffeb79835ede4a0b285078036R617 where I clarified which dependencies are provided OOTB, optionally or are embedded.

**Review by davidjgonzalez — DISMISSED** [review]

**Review by davidjgonzalez — COMMENTED** [review]
See kwin comment

**Comment by davidjgonzalez** [comment]
@joerghoh @kwin @justinedelson  we OK closing this issue without merging?

**Comment by kwin** [comment]
Let's close this, as we don't embed aws-sdk!

**Pull request closed without merging**
