### PR TITLE
Created Email object PER recipient to resolve #462

### LINKED ISSUE #462: Issue with email service
1. If we have more than one recipients. The second recipient is getting one attachment which is the mail template. Third recipient gets two attachments etc. This is the behaviour in outlook.

2. When we are sending mail to gmail or other. Second recipient getting two mails. Third receipt getting three mails etc.

### PR DESCRIPTION
**Pull request by davidjgonzalez**
Resolves #462 

@maximilianvoss can you please review? Thanks

----
If we have more than one recipients. The second recipient is getting one attachment which is the mail template. Third recipient gets two attachments etc. This is the behaviour in outlook.

When we are sending mail to gmail or other. Second recipient getting two mails. Third receipt getting three mails etc.

### CODE REVIEW

**Comment by davidjgonzalez** [comment]
@dchang this may be of interest to you as well on current proj

**Comment by dchang** [comment]
Thanks for the heads up @davidjgonzalez ! Looks like we used this email service in several places, will keep this fix in mind

**Comment by maximilianvoss** [comment]
Actually I would have patched just following:

````
        Email email = getEmail(templatePath, emailParams);

        if (email == null) {
            throw new IllegalArgumentException("Error while creating template");
        }

        MessageGateway<Email> messageGateway = messageGatewayService.getGateway(email.getClass());

        for (InternetAddress address : recipients) {
            try {
                email.setTo(Collections.singleton(address));
                messageGateway.send(email);
            } catch (Exception e) {
                failureList.add(address);
                log.error("Exception sending email to " + address, e);
            }
         }

        return failureList;
````
to
````


        MessageGateway<Email> messageGateway = messageGatewayService.getGateway(email.getClass());

        for (InternetAddress address : recipients) {
            try {
               Email email = getEmail(templatePath, emailParams);
               if (email == null) {
                     throw new IllegalArgumentException("Error while creating template");
                }
                email.setTo(Collections.singleton(address));
                messageGateway.send(email);
            } catch (Exception e) {
                failureList.add(address);
                log.error("Exception sending email to " + address, e);
            }
         }

        return failureList;
````

It's the easier fix and not too much has to be touched. 
__WDYT?__

**Comment by davidjgonzalez** [comment]
@maximilianvoss I made the more significant changes to minimize interactions w the data store. caches exist, but this guarentees 1 IO read for an unbounded recipient size.

**Comment by maximilianvoss** [comment]
@davidjgonzalez indeed, your solution makes a lot more sense then :)

**Pull request merged**
