### PR TITLE
Add more granular environment indicator css control - take 2

### PR DESCRIPTION
**Pull request by paul-bjorkstrand**
New PR (superseding #2018), updating the existing branch seemed a little ugly, so I created a new one

* enables the ability to always include the base CSS (regardless if cssOverride is set)
* enables the ability to always include the background color CSS (regardless if cssOverride is set)
* separates the three components of the CSS into separate style rules, making it easier to use common to all environments override CSS in conjunction with a custom CSS background color
* keeps backwards compatibility intact

### CODE REVIEW

**Comment by paul-bjorkstrand** [comment]
@badvision and @davidjgonzalez, I gave up on the AssertJ problem from the old PR, and (begrudgingly) rewrote this with Hamcrest and vanilla Junit. I also cleaned up the extraneous files as well.

**Comment by davidjgonzalez** [comment]
What’s with those marketo commits?

**Comment by paul-bjorkstrand** [comment]
@davidjgonzalez the build was failing because of the baseline plugin (telling me to up the versions)

**Comment by paul-bjorkstrand** [comment]
So, I blindly obliged, perhaps in error. I just wanted it to build locally :)

**Pull request merged**
