### PR TITLE
Add common LOCALE in SpreadsheetTest

### PR DESCRIPTION
**Pull request by reggie7**
This way different machines will react in the same way to the tests.

I've had test failures, when running from a machine with Polish locale.

### CODE REVIEW

**Comment by badvision** [comment]
Sorry, I only tested in reverse-Polish

**Comment by reggie7** [comment]
@badvision - is it ok for merge like that?

**Comment by csaboka** [comment]
#1864 is trying to solve the same issue, but by allowing a locale to be specified for Spreadsheet instead of forcing a specific global locale during test execution.

**Comment by reggie7** [comment]
@csaboka I'm all cool with #1864, but it's been a while with no fix and I think my quick workaround would suffice in short run before the full solution gets in place finally. Meanwhile it's pretty annoying to work with this test failing :(

**Comment by kwin** [comment]
@reggie7 I merged #1864 which should make this PR obsolete. Can you quickly cross-check and then close this PR?

**Comment by reggie7** [comment]
@kwin - this particular test succeeds finall @ my machine, but the `master` does not compile properly as a whole anymore for me neither in `J8` nor in `J11`. But no worries, let me check tomorrow more deeply maybe it's some local issue.

**Comment by reggie7** [comment]
Yup, works fine on a clean `master`. Thanks!

**Pull request closed without merging**
