### PR TITLE
Added locale object, injected from resource page, with sling request …

### PR DESCRIPTION
**Pull request by niekraaijmakers**
Slight extension that adds Locale to the AemObject injector, injecting Locale based on resource Page, with slingrequest as fallback.

### CODE REVIEW

**Comment by badvision** [comment]
Can you add a unit test method for the resolveLocale logic @niekraaijmakers ?   Thanks so much! :D

**Comment by niekraaijmakers** [comment]
too difficult for this one, because aem context / sling context don't support getContainingPage on the resourceResolver :( not sure how to test this?

**Comment by badvision** [comment]
You can just use mockito to make a fake object that returns something... really you just want to trigger expected behaviors in the method to ensure all the conditional logic works like it should.

**Comment by niekraaijmakers** [comment]
ok sir :) because you asked

**Pull request merged**
