### PR TITLE
TouchUI RTE Color Picker Plugin

### PR DESCRIPTION
**Pull request by schoudry**
@davidjgonzalez @justinedelson 

Color Picker Plugin for TouchUI RTE

Demo - https://drive.google.com/file/d/0B4d6KmbLkAumc1J1Z0Etckd3NDQ/view?usp=sharing

1) Enable color picker feature

image

2) Configured colors - /apps/acs-commons/dialogs/color-picker-popover/cq:dialog/content/items/column/items/picker/colors

image

3) Color Picker in RTE

image

4) Color Applied

image

5) HTML source

image

### CODE REVIEW

**Comment by HitmanInWis** [comment]
@schoudry Can you verify that this plugin works in Firefox?  When I implemented colorpicker from your post at http://experience-aem.blogspot.com/2015/10/aem-61-touchui-rich-text-editor-color-picker-plugin.html I needed to replace:
`return winSel && winSel.type && winSel.type.toUpperCase() == "RANGE";`
with:
`return winSel && winSel.rangeCount == 1 && winSel.getRangeAt(0).toString().length > 0;`
for this to work in Firefox.

**Comment by schoudry** [comment]
@HitmanInWis not yet; can you submit another pull with the fix for firefox after this gets merged

**Comment by HitmanInWis** [comment]
@schoudry I sure can.

**Comment by schoudry** [comment]
pulling back for now until we have a better solution for extending rte

**Pull request closed without merging**
