### PR TITLE
Moving reports from /var/acs-commons/reports to /conf/acs-commons-reports

### LINKED ISSUE #2341: ACS Commons fails to deploy to AEM as a Cloud Service due to inclusion of /var nodes
## Required Information

**Originally reported with clear description of symptoms by @stefanseifert  at: https://github.com/Adobe-Consulting-Services/acs-aem-commons/issues/2334**

* [X] AEM Version, including Service Packs, Cumulative Fix Packs, etc: AEM as a Cloud Service
* [X] ACS AEM Commons Version: 4.x.x
* [X] Reproducible on Latest? yes

ACS AEM Commons fails to deploy to AEM as a Cloud Service because AEM's replication service user does not support replication (due to permissions of the service user) or nodes under /var, which the ACS Commons `ui.content` project has.

image

These nodes should should be establishing using repoinit scripts (targetting the minimal runmodes) as needed. This looks trivial for all nodes EXCEPT `/var/acs-commons/reports` which contains cq:Page definitions (which are large, and complex in structure).

@klcodanr is there a reason these nodes are in `/var`? It actually seems strange these are in `/var` which historically has more transient, runtime content (these appear to be report definitions). Thoughts on if they could be easily moved outside of `/var`?

Also, can you help me confirm:

- [x] `/var/acs-commons/httpcache` -> Should exist on Author and Publish (@niekraaijmakers)
- [ ] `/var/acs-commons/mcp` -> Should exist only on Author (@badvision)
- [x] `/var/acs-commons/on-deploy-scripts` -> Should exist on Author and Publish (@HitmanInWis)
- [ ] `/var/acs-commons/reports` -> Should exist only on Author (@klcodanr)

The working PR to resolve this is at: https://github.com/Adobe-Consulting-Services/acs-aem-commons/pull/2342

### PR DESCRIPTION
**Pull request by klcodanr**
To resolve #2341 

Old reports are still accessible and can simply be copied from /var to /conf

### CODE REVIEW

**Comment by klcodanr** [comment]
@davidjgonzalez -- could you take a look at this? It's to resolve #2341

**Comment by davidjgonzalez** [comment]
@klcodanr LGTM - just want to make sure `/conf` is the best place for this stuff... 

Relates to: https://github.com/Adobe-Consulting-Services/acs-aem-commons/issues/1909 and 
https://github.com/Adobe-Consulting-Services/acs-aem-commons/issues/2354

See like we can:

+ Keep stuff in `/etc/acs-commons`
+ Move stuff to `/conf/acs-commons` (similar to generic lists v2), the oddity here is this stuff is generally not context aware configurations.
+ Move stuff to `/content/acs-commons` if we can figure out how to hide that from the normal Site admin (which im not sure how to do)

**Comment by joerghoh** [comment]
I don't understand that report builder feature that good (haven't used it at all), but why can't we ship the the feature in /apps (the report page itself and also the default reports) and create custom reports in /conf?

**Comment by davidjgonzalez** [comment]
@joerghoh - The Reports listing UI is already under /apps. Shipping the samples under /apps would make them read-only of course, so we 'd need to handle that, which is more code/change to this feature.
This Issue is to make minimal changes to this feature to make it AEM CS compatible (ie. removing the samples from /var).

My updates to this branch moved the content from /conf to /etc --  Simply because that's where everything else "like this" in ACS Commons writes to today (except Generic Lists v2), and we dont know yet where they will ultimately live (maybe /conf/acs-commons, maybe not). Atleast in /etc/acs-commons we should be able to perform a bulk "lift-and-shift" (w/ hopefully a simple migration mechanism) to whatever the new location is. If we fragment where this stuff lives, that "lift-and-shift" becomes harder (unless we've serendipitously picked the right place)

**Comment by davidjgonzalez** [comment]
@klcodanr Any major concerns storing reports in `/etc/acs-commons` for now until we can figure out where all that stuff needs to ultimately get moved to?

Also, neither here nor there, but I removed reports from the ACS Commons TouchUI console since when I opened up a Report page for editing from it, I got an error saying AEM couldn't resolve `/bin/editor` .. and I didn't jump out to me where that was being defined (is that an details specific to Reports?) -- More curious that anything :)

**Comment by klcodanr** [comment]
@davidjgonzalez I do :-( the big problem is that due to some hardcoding shenanigans in the WCMMode filter you cannot use touchui under /etc: https://blogs.perficient.com/2017/11/16/no-matter-what-a-anyone-tells-you-theres-no-touchui-under-etc/

**Comment by davidjgonzalez** [comment]
Ah - ok. I'll revert!

**Comment by davidjgonzalez** [comment]
@klcodanr reverted the change (left a fix in for the notification positioning)

**Comment by klcodanr** [comment]
@davidjgonzalez @joerghoh -- where did we land on this? This one has been floating out here for awhile...

**Pull request merged**
