### PR TITLE
CCVAR: Fixed Same Attribute not updating correctly

### PR DESCRIPTION
**Pull request by vabs95**
Defect: CCVAR Same Attribute doesn't update all placeholders in the value.

Uses the original attribute value and only updates the last placeholder value leaving the other placeholders as it is. 

Example: 

 Attr "title=((custom_prefix)) ((custom_title))"

Expected: "title=Prefix Title"

Actual: "title=((custom_prefix)) Title"

Solution: Update the currentAttr Value with new attrValue when looping placeholders.

### CODE REVIEW

**Comment by csaboka** [comment]
@vabs95 : JUnit 4 tests are not running at the moment, I'm trying to fix that in #3273 . Since the test you are trying to extend uses JUnit 4 tools, it doesn't run at all and won't contribute to coverage no matter what you change.

You can either wait until #3273 is merged, or try rewriting the test class to JUnit 5.

**Comment by vabs95** [comment]
@csaboka Can you please review it now?

**Comment by csaboka** [comment]
@vabs95 : I'm not a project owner, just a minor contributor to the project. I'm not familiar with the code you touched, but even if I were, my approval wouldn't be enough to allow merging this.

**Comment by vabs95** [comment]
@kwin  can you please review it ?

**Review by davidjgonzalez — APPROVED** [review]

**Comment by vabs95** [comment]
@davidjgonzalez  can you please re-run the checks?

**Comment by vabs95** [comment]
hi @davidjgonzalez can you please merge this now? It has been pending for a long time.

**Pull request merged**
