### PR TITLE
issue-651 added default value for classValuePrefix in icon picker

### PR DESCRIPTION
**Pull request by viveksachdeva**
Issue:
https://github.com/Adobe-Consulting-Services/acs-aem-commons/issues/651

Changes Made:
- Added default value for classValuePrefix is js plugin.

 Ready for review..

### CODE REVIEW

**Comment by viveksachdeva** [comment]
@justinedelson : I created this branch over 6.2 compatibility branch... is that right or should it be over master and 6.2 will be rebased over master in case this one works as expected?
Thanks!!

**Comment by davidjgonzalez** [comment]
PRs that apply to both master and 6.2 compat should be branched from and made against master. Once merged into master, we pull master into 6.2 compat.  6.2 only features/fixes can go straight into 6.2 compat branch and not master.

**Comment by justinedelson** [comment]
that said, since this is a trivial change, I'll just fix it manually.

**Comment by justinedelson** [comment]
manually merged. thanks!

**Pull request closed without merging**
