### PR TITLE
update to latest sling mock versions

### PR DESCRIPTION
**Pull request by justinedelson**

### CODE REVIEW

**Comment by badvision** [comment]
It looks like some of the tests are failing with the same root cause:
`java.lang.RuntimeException: Unable to invoke method 'bindAdapterFactory' for class org.apache.sling.testing.mock.sling.MockAdapterManagerImpl
Caused by: java.lang.NoSuchMethodError: org.apache.sling.adapter.internal.AdapterFactoryDescriptor.<init>`

**Comment by justinedelson** [comment]
@badvision do you have a specific example? Does that happen on the CLI or in your IDE?

**Comment by badvision** [comment]
No I was just reading the log from the failed build via Travis CI -- I haven't tried to build with this change yet.

**Comment by justinedelson** [comment]
weird. I can't reproduce locally. I'll try moving the dependencies around

**Comment by justinedelson** [comment]
looks like it is working now after removing the old testing dependency

**Pull request merged**
