### PR TITLE
526 - Error Page Handler - Corrects page resolution

### PR DESCRIPTION
**Pull request by davidjgonzalez**
Resolves aggregate note resolution as described in #526 

@justinedelson  can you sanity check the rr.resolve(..) for any sling mapping corner-cases?

@apoorv81 can you test this PR out and see if resolves your issue (it should)

### CODE REVIEW

**Comment by davidjgonzalez** [comment]
@umeshtiwari23  i think this will resolve your issue; could you try it out?

**Comment by umeshtiwari23** [comment]
@davidjgonzalez Yes i tried putting your logic and it is working fine for mapped urls.

**Comment by ajaykpaul** [comment]
it seems it is still not working for 500 for the release 2.0.2, are there any config changes ?

**Comment by davidjgonzalez** [comment]
@ajaykpaul you would need to pull this branch and install -- this PR is not merged yet so its not in any release - I can create a content package if thats easier.

**Comment by davidjgonzalez** [comment]
@ajaykpaul here is the package from the PR

min package: https://dl.dropboxusercontent.com/u/17017/acs-aem-commons-content-2.0.3-SNAPSHOT-min.zip

non-min package: https://dl.dropboxusercontent.com/u/17017/acs-aem-commons-content-2.0.3-SNAPSHOT.zip

**Comment by apoorv81** [comment]
Hi @davidjgonzalez 

I've just checked and the this fix resolves the issue I raised, it is able to find the 500 page now.

Thanks
Apoorv

**Pull request merged**
