### PR TITLE
Added new UI to submit queries and bulk update/insert/delete properties

### PR DESCRIPTION
**Pull request by steffenrosi**
Added new UI to submit queries and bulk update/insert/delete properties

Go to http://localhost:4502/etc/acs-commons/bulk-editor.html to test

screenshot 2014-12-22 11 53 24
screenshot 2014-12-22 11 55 33

### CODE REVIEW

**Comment by ronnyfm** [comment]
Was this accepted into ACS AEM Tools?

**Comment by steffenrosi** [comment]
@davidjgonzalez, to my knowledge, this has not been included. WDYT, would this be an addition or is this pretty much covered by other functionality? I thought something similar was developed by you a while ago...

**Comment by davidjgonzalez** [comment]
@steffenrosi yeah .. ended up getting to complicated for the time/attention i had :( ... if you have yours around we could pull that in? I know one of the (sage) pieces of feedback from @justinedelson was to create a dry-run mode considering the absolute, repository wrecking power of this thing.

Sort of related, i updated CSV Asset Importer to be able to update properties; the problem is there isnt any good way to get the properties out into CSV format right now.

WDYT? How hard would it be to add a preview/dry-run to yours?

**Comment by steffenrosi** [comment]
@davidjgonzalez should't be a big deal to include a preview/dryrun mode... Trying to look into it next week, hopefully.

**Pull request closed without merging**
