### PR TITLE
Resolving #1413 - Fixing Issue where Redirect Manager Not Accessible on Publish

### PR DESCRIPTION
**Pull request by klcodanr**
By making /etc/acs-commons/redirect-maps globally readable

### CODE REVIEW

**Comment by davidjgonzalez** [comment]
@klcodanr this ACL effects both Author and Publish... there's no concerns with this right?

Is there anything special w/ filter.xml thats required?

**Comment by davidjgonzalez** [comment]
@klcodanr if you have a sec - can you confirm there's nothing missing here? I have to run out for about an hour but would like to cut a release when i get back - @lrochefort has been patiently waiting for weeks for a new release :)

**Comment by klcodanr** [comment]
hey @davidjgonzalez sorry I was in an all day workshop. 

So yes, the idea is for the ACL to be applied in Publish & Author. For author, the user still must be authenticated and for publish the Redirect Maps need to be accessible to be read by the Dispatcher server. 

I just installed the package into a local instance and the ACL installs successfully.

**Comment by davidjgonzalez** [comment]
Travis failure due to timeout of some of the builds.

**Pull request merged**
