### PR TITLE
backport srcset support to 2.x branch

### PR DESCRIPTION
**Pull request by justinedelson**
@insideaem can you test this out?

### CODE REVIEW

**Comment by insideaem** [comment]
Ok will test over the weekend and give feedback.
Thanks

**Comment by insideaem** [comment]
ok I have tested it and it looks good.
Thanks for realeasing.

**Comment by insideaem** [comment]
Hey @justinedelson 
Any idea when you plan to release this change? What would be the version number?

Cheers,
Nono

**Comment by justinedelson** [comment]
The version number would be 2.14.0.

**Comment by insideaem** [comment]
ok thanks. And any idea when you could release it?

**Comment by justinedelson** [comment]
I'll do the release now, but I'd really suggest that you get off AEM 6.1 :)

**Comment by insideaem** [comment]
Thanks,
Client will be moving in the next months to 6.3 ;-)
Untill then we are stuck with using the 2.xx version.

Cheers,
Nono

**Pull request merged**
