### PR TITLE
#768 - Move property copy to use JCR-based APIs to preserve property …

### PR DESCRIPTION
**Pull request by davidjgonzalez**
…types (namely Name[])

@catholicon can you check this out?

6.0/6.1 builds are here:

[acs-aem-commons-content-2.6.5-SNAPSHOT-min.zip](https://github.com/Adobe-Consulting-Services/acs-aem-commons/files/400568/acs-aem-commons-content-2.6.5-SNAPSHOT-min.zip)
[acs-aem-commons-content-2.6.5-SNAPSHOT.zip](https://github.com/Adobe-Consulting-Services/acs-aem-commons/files/400569/acs-aem-commons-content-2.6.5-SNAPSHOT.zip)

### CODE REVIEW

**Comment by catholicon** [comment]
@davidjgonzalez for working this out so fast. I didn't have a a 6.0/1 setup at my disposal. So, I cherry-picked this for 6.2. It worked like a charm :).

**Comment by davidjgonzalez** [comment]
@catholicon awesome! sorry - i figured your proj was on 6.1..

I think @justinedelson cut 3.2.6 yday, so we'd need a 3.2.8..  @catholicon how soon you need this? cut today in hopes for hitting adobe repo tomorrow (though might take till mon/tues depending on support availability)

**Comment by catholicon** [comment]
The project is in 6.0... But, I just had my laptop with me.

@davidjgonzales, if cutting today is acceptable, then that would be pretty awesome. But it'd fine to have it somewhere next week too. I won't need it off of Adobe repo... Github link of the release package is perfectly ok.

**Comment by davidjgonzalez** [comment]
@catholicon will target today; probably after work since today is busy.

**Comment by catholicon** [comment]
Thanks for the swift response (as always) :)

**Pull request merged**
