### PR TITLE
#2282 disable features on AEM as a CloudService

### PR DESCRIPTION
**Pull request by joerghoh**

### CODE REVIEW

**Comment by royteeuwen** [comment]
Sad that the versioned clientlibs does not work, it's a really handy one for javascript invalidation. Can this one be fixed or is it inherently bad design for AEM aaC?

**Comment by davidjgonzalez** [comment]
@royteeuwen this should be OOTB now in AEMaaCS.

**Comment by joerghoh** [comment]
Well, some testing is still outstanding :-) Plan to work on it later today on a quickstart instance and a AEMaaCS SDK instance.

**Comment by badvision** [comment]
@joerghoh did you want to hold off on the merge until after you do more testing?

**Comment by joerghoh** [comment]
Yes, I do. Please don't merge until further notice.

**Comment by joerghoh** [comment]
I tested locally with AEM 6.5.2 and the listed components are active. After overcoming some issues unrelated to this change I was able to confirm, that these components are not active on a recent SDK version.

So all fine, we can go on and merge.

**Comment by davidjgonzalez** [comment]
@joerghoh any idea if these are marked as incompatible on the ACS Commons docs site? I wonder if we should change the wording on these to state that they won't start on AEM CS (vs. saying they are incompatible, so don't use them.... now you *cant* use them)

**Comment by joerghoh** [comment]
https://github.com/Adobe-Consulting-Services/adobe-consulting-services.github.io/pull/195

**Pull request merged**
