### PR TITLE
Fixed cache refresh on versioned clientlibs request when enforceMd5 is false

### LINKED ISSUE #2562: Clientlibs unneeded cache refresh
## Required Information

* [x] AEM Version, including Service Packs, Cumulative Fix Packs, etc: 6.5.6.0
* [x] ACS AEM Commons Version: 4.6.0
* [x] Reproducible on Latest? yes

### Expected Behavior

When enforceMd5 is switched off (default behaviour), a cache hit should not trigger a cache refresh of a clientlib.

### Actual Behavior

When enforceMd5 is switched off, a cache refresh is triggered when the md5sum is present in the url. A message like:
```
com.adobe.acs.commons.rewriter.impl.VersionedClientlibsTransformerFactory Refreshing client libraries cache, because /etc.clientlibs/some/client/lib.min.b75fbc620015773fc1a9e5b000ac77b6 could not be found
```
is logged.

### Steps to Reproduce

1. Enable versioned clientlibs as documented
2. Request any page from AEM with clientlibs on it
3. Refresh the page a few times, so the versioned clientlib is requested and cached
4. You see the message logged on every request

### PR DESCRIPTION
**Pull request by wimsymons**
- Fix wrong url's in tests where enforceMd5 is false (default)
- Added extra test for cache hit when enforceMd5 is true
- Verify no cache refresh is executed on a cache hit
- Fixed #2562 getUriInfo splitting the url incorrectly when enforceMd5 is false
- Added entry to CHANGELOG.md

### CODE REVIEW

**Comment by wimsymons** [comment]
Travis failed to check out the project on OpenJDK 11:
```
fatal: unable to access 'https://github.com/Adobe-Consulting-Services/acs-aem-commons.git/': The requested URL returned error: 429
```

**Comment by wimsymons** [comment]
Closing for travis re-trigger

**Comment by wimsymons** [comment]
Opening for travis re-trigger

**Comment by wimsymons** [comment]
@davidjgonzalez could you do a review? Or who else could do that?

**Review by davidjgonzalez — APPROVED** [review]

**Pull request merged**
