### PR TITLE
Feature/bugfix multifield support arrays

### PR DESCRIPTION
**Pull request by badvision**
Bugfix for #1730

### CODE REVIEW

**Comment by justinedelson** [comment]
@badvision I think this needs to be rebased.

**Comment by badvision** [comment]
boy howdy... yeah I'm still working on it but that's a good idea.

**Comment by badvision** [comment]
That was one ugly rebase but I think we're in the clear on this branch.  I'll do some additional testing to be sure.  It also probably needs more test coverage before I can call it done because there was some additional logic added.

**Comment by justinedelson** [comment]
don't feel great about merging this because of the decrease in coverage (despite my last ditch effort there to increase the coverage by testing the Select component), but it is a major API change so better to do it with 4.0 than wait.

**Pull request merged**
