### PR TITLE
Fix for issue 2314

### PR DESCRIPTION
**Pull request by sromazanov**
https://github.com/Adobe-Consulting-Services/acs-aem-commons/issues/2314

### CODE REVIEW

**Comment by joerghoh** [comment]
do you think that a proper unittest makes sense here?

**Comment by davidjgonzalez** [comment]
Merged. If someone wants to make a unit test for this, by all means, but it's probably time better spent writing a test for a non-deprecated feature; I dont think there will be much ROI writing new tests for this feature.

**Comment by sromazanov** [comment]
Could you include this fix to 4.7.2 milestone please?

**Comment by davidjgonzalez** [comment]
You got it. FYI I’d like to try to cut a release this week for 4.7.2 - need to find time to validate a copy properties wf fix.

**Pull request merged**
