### PR TITLE
solr resource provider

### PR DESCRIPTION
**Pull request by dherges**
for time being, a very minimalistic sample that shows how to do to expose solr documents to the sling resource tree ... can't query for now ... can't persist for now ... just a play of mind on a friday :-)

### CODE REVIEW

**Comment by davidjgonzalez** [comment]
@dherges basic question .. is this better for ACS AEM Samples? 

How fully featured is this (it looks more like a shell for others to impl on top of?)

**Comment by dherges** [comment]
@davidjgonzalez 

> is this better for ACS AEM Samples?

Yes, probably yes. I'd like to make work...
- findResources() and queryResources() with "/select" API
- create() and commit() with "/update" API 

.. and then it's really more of a nutshell .. can also be a sample for others to implement resources from an elasticsearch or something

**Comment by dherges** [comment]
we can close this PR, i'll try to get a line of code ... or two ... published on github here ..  https://github.com/dherges/acs-aem-samples/tree/feature/solr-resources .. on the occasion from time to time

**Comment by davidjgonzalez** [comment]
Closing for move to ACS Samples

**Pull request closed without merging**
