### PR TITLE
Feature / HTTP cache

### PR DESCRIPTION
**Pull request by Sivaramvt**
HttpCache caches the full output of a http request per the configurations and then bypass the request processing entirely on each subsequent requests achieving high performance.  
### Features
* Caches anonymous and authenticated requests.
* Supports caching personalized requests. Group based caching provided OOTB. Mechanism exposed to plugin custom logic for handling personalized requests.
* Flexible cache configs tied to URIs supported. Allows extending cache configs. Allows multiple cache configs.
* Developer hook exposed to plugin custom rules on key cache handling events such as request receive, response cache, response deliver and cache invalidate.
* Provides mechanism to plugin custom cache keys.
* Pluggable cache persistence model. In-Memory implementation provided OOTB. Allows multiple cache stores to co-exist.
* Invalidation mechanism based on JCR paths and Sling jobs. Sample JCR change event handler based invalidation supplied. In-Memory cache store supports TTL.
* Provides instrumentation based on JMX mbeans.   

Credits to @davidjgonzalez for this wonderful idea, contribution and guidance.

Please review.

### CODE REVIEW

**Comment by davidjgonzalez** [comment]
FYI - going to try to merge the servlet changes into your branch now

**Comment by Sivaramvt** [comment]
Looks like there is a conflict in bundle/pom.xml

**Comment by davidjgonzalez** [comment]
@Sivaramvt added some Felix namehints for config factories so life in 6.2 is nice. Moved off the default diamond so we can keep 1.6 for now (probably doesnt matter, but was a benign change and were changing a bit already this release).. lets see what Travis says....

**Comment by Sivaramvt** [comment]
Thanks @davidjgonzalez . Super excited that this work would be used by bigger community.

**Pull request merged**
