### PR TITLE
Adding capability to update multi-valued references for Renovator

### PR DESCRIPTION
**Pull request by mxp737**
#2439 Enhancement : Ability to update asset references in components which have the paths as a list or Array[]

### CODE REVIEW

**Comment by axp235** [comment]
@badvision : Please review and provide feedback

CC : @mxp737

**Review by badvision — APPROVED** [review]
Looks good to me.  Thank you for also adding test coverage!

**Review by badvision — APPROVED** [review]

**Comment by axp235** [comment]
@davidjgonzalez / @badvision : Can you please consider this as a bug for release "4.9.0"?

CC: @mxp737

**Comment by davidjgonzalez** [comment]
@axp235  - yup! this is in. master so it will go out w/ 4.9.0

**Pull request merged**
