### PR TITLE
Switch JsonEventLogger and SyslogAppender to OSGi R6 Annotations.

### PR DESCRIPTION
**Pull request by adamcin**
Contributes to completion of #1666

### CODE REVIEW

**Comment by adamcin** [comment]
@badvision I'm still working on improving code coverage. I'll let you know when it's ready to merge.

**Comment by badvision** [comment]
More code coverage coming?  SQUEEEE! 😀

**Comment by adamcin** [comment]
@badvision as soon as these checks pass you can merge this PR.

**Comment by badvision** [comment]
[https://media1.tenor.com/images/80ef5f4ee78efaf8a609c679cc2bd587/tenor.gif?itemid=5217424](Totes Magotes)

**Pull request merged**
