### PR TITLE
Adding clientlib category to enable icon picker also for create page …

### PR DESCRIPTION
**Pull request by tnebe**
…dialog

### CODE REVIEW

**Comment by justinedelson** [comment]
I think `granite.ui.coral2.foundation.addons` would make more sense. @tnebe does that work for you?

**Comment by tnebe** [comment]
Hi @justinedelson, just tested but unfortunately not working with `granite.ui.coral2.foundation.addons`

**Comment by justinedelson** [comment]
sorry, bad copy & paste. The correct category is `granite.ui.coral.foundation.addon.coral2`

**Comment by tnebe** [comment]
Yeah! This category works fine, will update the PR accordingly. Thank you @justinedelson!! :)

**Comment by justinedelson** [comment]
Thanks!

**Pull request merged**
