### PR TITLE
use "mvn oakpal:webster" to update nodetypes.cnd, privileges.xml, and checklists.

### LINKED ISSUE #1872: Create process to update OakPAL checklist
Pulling up from comment in https://github.com/Adobe-Consulting-Services/acs-aem-commons/pull/1566#issuecomment-487933524

We should definitely have a way of generating this automatically.

@adamcin can you advise?

### PR DESCRIPTION
**Pull request by adamcin**
resolves #1872 

- in your maven settings.xml file, create two new profiles:
webster-aem64 and webster-aem65. In each, set a "webster.repositoryHome"
property with the absolute path to the
`crx-quickstart/repository` directory for a local AEM 6.4
and 6.5 server intallation, respectively.
- in the content module, run "mvn oakpal:webster -Pwebster-aem65" to
update the nodetypes.cnd and privileges.xml files with any AEM 6.5 definitions
referenced by qualified name by files in the filevault archive root
(src/main/content/jcr_root). This should be performed regularly as
existing content is changed, and as new content is added to the content package.
- in the oakpal-checks, run "mvn oakpal:webster -Pwebster-aem64" and "mvn
oakpal:webster -Pwebster-aem65" to keep the forced roots in the content classifications
checklists up to date. This will likely only need to be performed when
features are added to the checklists, or when service packs are
released.

### CODE REVIEW

**Comment by adamcin** [comment]
This Webster feature is still in release-candidate-stage while I work on writing up documentation for usage, but here is the maven goal page for it: http://adamcin.net/oakpal/oakpal-maven-plugin/webster-mojo.html

**Comment by adamcin** [comment]
@justinedelson @kwin Please review when you get a chance.

**Comment by adamcin** [comment]
@justinedelson @kwin I've completed the oakpal-1.3.0 release. Site documentation for webster has been added to http://adamcin.net/oakpal, with a good starting point here: http://adamcin.net/oakpal/oakpal-maven-plugin/webster-managing-nodetypes.html

**Comment by justinedelson** [comment]
@adamcin this looks great. Would you mind adding the information in the description to the README project, maybe in a new section called "Updating OakPAL Checklists" (could be in just the `oakpal-checks` module, but since the instructions span both `content` and `oakpal-checks` modules, putting it in the root README makes more sense to me.

Regarding:

bq. This should be performed regularly as
existing content is changed, and as new content is added to the content package.
bq. This will likely only need to be performed when
features are added to the checklists, or when service packs are
released.

Would it make sense to add this to the RELEASING file and just establish it as something that happens as part of every minor release (no need to do these for patch releases AFAICT).

**Comment by adamcin** [comment]
@justinedelson Thanks, I think that makes sense. I'll make the changes to the documentation in a separate PR after this is merged. @davidjgonzalez can you merge this please?

**Pull request merged**
