### PR TITLE
Touch UI Composite Multifield

### PR DESCRIPTION
**Pull request by schoudry**
sorry guys for the new pull, rebasing upstream acs commons caused some confusion with more commits getting added to the pull (i generally do merge ), closed it and created new.. i think i never understand a clean way of getting things done with git :)

### CODE REVIEW

**Comment by justinedelson** [comment]
I suspect the issue is that you are creating a pull request from your
master branch. You should do this from a feature branch in the future.

**Comment by schoudry** [comment]
got it, some day i am gonna create a blog "thanks justin" capturing all your replies ;)

**Comment by davidjgonzalez** [comment]
@schoudry @justinedelson this good to merge? Looks like @schoudry resolved the extra commits.

**Comment by schoudry** [comment]
hey @davidjgonzalez i think so unless there are no other comments

**Pull request merged**
