### PR TITLE
Fixes 1154

### PR DESCRIPTION
**Pull request by schoudry**

### CODE REVIEW

**Comment by srinm** [comment]
Hi @schoudry , thank you.
This fixed the issue with storing to jcr, Now i see no additional characters added 
but the dialog would not get populated on edit. Not sure if it has any dependency with version i'm using version 3.10.

**Comment by schoudry** [comment]
@srinm please attach the component

**Comment by srinm** [comment]
@schoudry  please find attached component code.
[evet-calendar-1.0.zip](https://github.com/Adobe-Consulting-Services/acs-aem-commons/files/1490709/evet-calendar-1.0.zip)

**Comment by justinedelson** [comment]
@schoudry did you confirm that this fixes the issue with @srinm's component?

**Comment by tearora** [comment]
I am also facing this issue  while using ACS commons 3.10.0 as dependency in the project.It is storing the values of Checkbox as <property_name>@Delete and value is also not retained in dialog edit.,

**Comment by srinm** [comment]
@justinedelson , @schoudry This pull request has resolved my issue with Json store regarding storgae of additional string(@) to jcr.
However i also had another issue with retaining the values in dialog after applying this fix. The dialog issue was resolved after resolving the dependencies.  I have already sent an email regarding the same last week. Thank you again for your support and quick responses.

**Comment by justinedelson** [comment]
@srinm I must have missed that email, but that's why we should try to communicate on this issue or #1154.

In any case, I don't really understand what you mean by "after resolving the dependencies". Are those dependencies of ACS AEM Commons or something else?

**Comment by justinedelson** [comment]
I've tested this locally and I think the patch is working correctly. So merging.

I did note that the attached package embeds a copy of several files from ACS AEM Commons. I had to remove these in order to get the fix working. I'm not sure why those files were copied, but that would make any fix impossible in this specific case.

**Pull request merged**
