### PR TITLE
Fix #2441 - Memory Exhaustion with Large Report Download

### LINKED ISSUE #2441: Report download servlet can exhaust the heap if the report is too large
## Required Information

* [x] AEM Version, including Service Packs, Cumulative Fix Packs, etc: 6.5.5
* [x] ACS AEM Commons Version: 4.4.0+
* [x] Reproducible on Latest? yes

### Expected Behavior

Custom reports from ACS Commons should have realistic limits to prevent generating reports that are too large to be of any value to the user; unbounded queries can inadvertently return a very large report by accident.

### Actual Behavior

Report size is unbounded, begin/end conditions should be more enforced; also the report download servlet should stream data out of JCR and into CSV not hold anything in memory.  This behavior combined with an overly-broad query killed a production server with a 40gb heap!

image

### Steps to Reproduce

Find a DAM instance with millions of assets.  Create a report with an end date but no start date.  Then try to download the report.  Watch server melt to molten slag.

### PR DESCRIPTION
**Pull request by klcodanr**
Primary Changes:

 - uses stream instead of getting results as a list
 - fixes a problem where the alert wasn't appearing when the result writing failed (made it a big red box instead of trying to show the toast)

### CODE REVIEW

**Comment by badvision** [comment]
I'm not too worried about 0.05% code coverage decrease, but any chance you can do a quick refactor to make code climate happy @klcodanr ?

**Comment by badvision** [comment]
If you're swamped, let me know.  Looks like this is in a branch I can push changes to as well.

**Review by badvision — APPROVED** [review]
Looks good to me!  Great usage of Streams!

**Comment by klcodanr** [comment]
Working on it now, I'll add a test for the getResultsList method and I _think_ that'll push the test coverage back up.

**Comment by badvision** [comment]
Thanks @klcodanr for your continued commitment to quality.

**Comment by badvision** [comment]
If you want to get the number up, add a test for ResultPage.equals to cover the various conditional cases.  I personally don't see how that's really all that valuable, but it would make the coverage go back up.  Thoughts, @klcodanr?

**Comment by badvision** [comment]
OK that also makes sense. ;)  Curious to see the final automated test result but I anticipate we're good and can move forward with this one once everything clears.  Thanks again @klcodanr!

**Review by badvision — APPROVED** [review]

**Comment by klcodanr** [comment]
Oops mean to leave this comment first. I looked into the codebase and found the QueryResults were not being checked for equality or put in a Map / Set so it seems safe to delete these methods.

**Comment by badvision** [comment]
That's fine.  Looks like code coverage is back where it should be.  In the meantime, builds are passing but there was one transient failure: https://travis-ci.org/github/Adobe-Consulting-Services/acs-aem-commons/jobs/737126569
I'm not convinced it was related though.

**Comment by klcodanr** [comment]
+0.01%

image

**Comment by badvision** [comment]
Yeah, I can ignore that random failed test in this case, it was with cloud config tests unrelated to this code change.  
`[ERROR] valid(com.adobe.acs.commons.cloudconfig.impl.CloudConfigurationListImplTest)  Time elapsed: 0.042 s  <<< ERROR!
java.lang.RuntimeException: Unable to initialize JCR_MOCK resource resolver factory: Unable to inject mandatory reference 'serviceUserMapper' for class org.apache.sling.resourceresolver.impl.ResourceResolverFactoryActivator : no matching services were found.
Caused by: org.apache.sling.testing.mock.osgi.ReferenceViolationException: Unable to inject mandatory reference 'serviceUserMapper' for class org.apache.sling.resourceresolver.impl.ResourceResolverFactoryActivator : no matching services were found.`

**Comment by badvision** [comment]
-0.03%  coverage?  I am confused.   Also ready to move on anyway.  Suggestions?

**Comment by klcodanr** [comment]
Huh, weird. Looks like the merge caused a slight drop in code coverage:
https://coveralls.io/builds/34287731 v https://coveralls.io/builds/34287298

Either way, it's close to even.

**Comment by badvision** [comment]
I think it's actually the test was returning a mock instead of calling the actual object method in this case.  I'll try this one-line change and see if it helps.

**Review by badvision — APPROVED** [review]

**Pull request merged**
