### PR TITLE
issue-812 fix for js error in validations - composite multifield

### PR DESCRIPTION
**Pull request by viveksachdeva**
Issue : https://github.com/Adobe-Consulting-Services/acs-aem-commons/issues/812

Can be reviewed.

cc @justinedelson , @davidjgonzalez

### CODE REVIEW

**Comment by justinedelson** [comment]
@schoudry  can you review this? seems simple enough

**Comment by schoudry** [comment]
@viveksachdeva looks good

**Comment by schoudry** [comment]
@viveksachdeva on second thought, can you remove the clear() call in show() and see if it works; i believe the framework calls "clear()" before executing show....

**Comment by justinedelson** [comment]
doh. I merged already. @schoudry does this need to be reverted?

**Comment by schoudry** [comment]
@justinedelson that's ok, nvm,  just wanted to check

**Pull request merged**
