### PR TITLE
Remove dependency to commons.lang for Cloud Service

### LINKED ISSUE #3421: Remove dependency on Apache Commons Lang 2 for Cloud Service
Apache commons lang 2 is not maintained anymore since years. Usage of it should be replaced with Apache Commons Lang 3. Both libraries are part of AEM as a Cloud Service and AEM 6.x-

ACS is currently using AEMs MailTemplate API which uses Commons Lang 2 API in the signatures. The latest Cloud Service release offers an alternative. This should be used for Cloud Service to completely remove the dependency to commons lang 2

### PR DESCRIPTION
**Pull request by cziegeler**
This fixes #3421

### CODE REVIEW

**Comment by cziegeler** [comment]
@kwin Do you think this is something for 7.0 due to requiring the latest CS release?

**Comment by cziegeler** [comment]
@kwin / @davidjgonzalez Can you please make sure that this gets included in 7.0 ?
Is there anything needed to be changed in this PR?

**Review by kwin — APPROVED** [review]

**Comment by kwin** [comment]
Fine for me, we don't yet have a branch/timeline for it nor any ETA. For now there is just this PR and https://github.com/Adobe-Consulting-Services/acs-aem-commons/pull/3406 which require raising prerequisites.

**Comment by davidjgonzalez** [comment]
@cziegeler - got back and looking at this now. Is it correct to stay:

1. This change is compatible with the current/latest version of AEM as a Cloud Service (which is 2024.9 at the time of writing).
2. Is this change compatible does not affect AEM 6.5 compatibility.

**Comment by cziegeler** [comment]
@davidjgonzalez Both is correct, requires one of the latest AEM CS versions - the changes are in for a month or so. It doesn't require a new AEM 6.5 version

**Comment by kwin** [comment]
Given that the latest ACS AEM Commons 6.7 already bumped the AEM Classic prerequisites to 6.5.21 I don't see a reason to defer this. AEMaaCS 2024.8 is reasonably old.

**Pull request merged**
