### PR TITLE
remove separate twitter bundle; use exception trapping to only regist…

### PR DESCRIPTION
**Pull request by justinedelson**
…er AdapterFactory when Twitter4J is available

### CODE REVIEW

**Comment by justinedelson** [comment]
Upon installation, if Twitter4J isn't available, you get a single log message:

```
com.adobe.acs.commons.twitter.impl.TwitterAdapterFactory Twitter4J Library not found. Not registering TwitterAdapterFactory.
```

Note that due to #1570, this isn't actually testable as-is.

Also, this pull request doesn't remove the `min` packaging. I think that warrants keeping around for legacy reasons.

**Comment by badvision** [comment]
Code climate strikes again... 🤕

**Comment by badvision** [comment]
We're doing a major version bump so we could remove it now, but after 4.0.0 it will be a while before we get another option to consider it.

**Comment by joerghoh** [comment]
+1 for removal of the twitter4j bundle, thus eliminating the need for the min bundle

**Comment by badvision** [comment]
I'll merge this in once the confirmation build passes (which I expect it to)

**Pull request merged**
