### PR TITLE
Feature/evaluate automated package replicator touchui #2087

### PR DESCRIPTION
**Pull request by JiangLong2019**

### CODE REVIEW

**Comment by klcodanr** [comment]
@JiangLong2019 Is there any reason to keep the angular front end if you're moving this out of /etc? The whole reason that was necessary was because of the strange limitations Adobe put on /etc.

**Comment by JiangLong2019** [comment]
Hi @klcodanr, since I couldn't find any front development guidelines in ACS commons, I just kept similar function with Report Builder. Any suggestions on this?

**Comment by klcodanr** [comment]
@JiangLong2019 - A few things seem off here:

- This PR does not change the location of the configurations from /etc
- There are some missed updates from the reports UI (+ Report)
- You can't edit the configurations
- The benefit of switching to TouchUI is that we could remove the custom Angular code to edit the configurations, this has not been done

APR

**Comment by JiangLong2019** [comment]
@klcodanr Thanks for the feedback! Let me add some comments inline.

>This PR does not change the location of the configurations from /etc
This was my concern while developing, should I change it to /conf?

>There are some missed updates from the reports UI (+ Report)
>You can't edit the configurations
I couldn't reproduce. Anyway, I plan to refactor it as you suggested we should go for TouchUI.

>The benefit of switching to TouchUI is that we could remove the custom Angular code to edit the configurations, this has not been done
OK, got it.

**Pull request closed without merging**
