### PR TITLE
#763 - Ensure Oak Index ignore property fixes

### LINKED ISSUE #763: Ensure oak index shouldn't wipe all properties at index-def node
There are a few properties [IGNORE_PROPERTIES](https://github.com/Adobe-Consulting-Services/acs-aem-commons/blob/master/bundle/src/main/java/com/adobe/acs/commons/oak/impl/EnsureOakIndexJobHandler.java#L84) which are currently used to identify if an index definition requires update or not.

BUT, when applying actual update, all props (apart from `jcr:primaryType`) from this list is wiped out.

Properties that are not factored while figuring out "something has changed" shouldn't be updated as well.

Note: removing reindexCount leads to [OAK-3629](https://issues.apache.org/jira/browse/OAK-3629)

### PR DESCRIPTION
**Pull request by davidjgonzalez**
Resolves #763 

@catholicon This looks like it'll do it.

### CODE REVIEW

**Comment by davidjgonzalez** [comment]
@catholicon We can change both`jcr:createdBy` and `jcr:lastModifiedBy`to be `session.getUserID()` ... im not sure why `jcr:createdBy` and `jcr:lastModifiedBy` would have different contracts in regards to valid values. This will get set as Admin for now (we dont have service users in Commons yet due to our support of 6.0)

**Comment by davidjgonzalez** [comment]
Also getting frustrated why travis is failing my test when it passes locally. :(

**Comment by davidjgonzalez** [comment]
@catholicon also, now that i think about it - i dont think the name of jcr:created or jcr:lastModifiedBy matters... you could very well have content w/ name values whose corresponding users have been deleted from the system.

**Comment by catholicon** [comment]
> i dont think the name of jcr:created or jcr:lastModifiedBy matters... you could very well have content w/ name values whose corresponding users have been deleted from the system. 
Good point. I liked a string value clearly mentioning ensure oak index... was just worried if might give some pain later on.

Let me try to run the tests at my end (currently, it's complaining that it doesn't like my mvn version - 3.0.5)

**Comment by catholicon** [comment]
> Let me try to run the tests at my end (currently, it's complaining that it doesn't like my mvn version - 3.0.5)

Sorry... works on my local setup too :-/

**Comment by davidjgonzalez** [comment]
@catholicon im going to comment it out the `@Test` for now and make a TODO for myself to figure it out later; dont have that much time left today and dont want to waste battling Travis.

**Comment by catholicon** [comment]
Sure, thanks :). Btw,
```
@Ignore("This test passes locally but fails on TravisCI; Figure out how to make this test pass on TravisCI")
```
might have been neater.

**Pull request merged**
