### PR TITLE
[REVIEW] Http cache JCR storage - 6.3

### PR DESCRIPTION
**Pull request by Sc0rpic0m**
I am doing something wrong with the service user. 

Somehow I get a constraint violation exception when installing and thus the user is not there.
Anybody that sees what I am doing wrong? I tried to copy the approach that other service users follow.

Much appreciated.

### CODE REVIEW

**Comment by Sc0rpic0m** [comment]
Thanks david! The issue is resolved & the module is working 100% fine on 6.3.

Now just have to solve the checks and we can pull it in.

**Comment by Sc0rpic0m** [comment]
Please check for review. The 8 issues to fix are trivial. Also, are powermock tests included in the coverage?

**Comment by davidjgonzalez** [comment]
@Sc0rpic0m are there areas (Files) the changed from the 6.0 PR to focus on? Thanks

**Comment by Sc0rpic0m** [comment]
Only real logic that changes was 
1) the service class, to use the service user
2) HttpCacheEngineImpl.java -> to adhere to sonar, reduce a little code. Definitely check this one just to make sure. But I tested the branch locally and it seemed fine, however better safe then sorry of course.

**Comment by davidjgonzalez** [comment]
Looks like a few minor codeclimage issues as well.

**Comment by davidjgonzalez** [comment]
Thanks @Sc0rpic0m !!

**Comment by Sc0rpic0m** [comment]
Not yet. Il contact david on how to extend the docs.

**Comment by justinedelson** [comment]
The documentation generated from https://github.com/Adobe-Consulting-Services/adobe-consulting-services.github.io. Please submit pull requests against that repository

**Comment by Sc0rpic0m** [comment]
Working on it. In meantime: basically this is just a jcr storage unit instead of in-mem (guava) storage unit for the http cache. Good side is it can handle large amounts of data and persist through restarts, downside its has a slower lookup.

**Pull request merged**
