### PR TITLE
#2679 wrap ReplicatorQueue in Replicator via java.lang.reflect.Proxy

### PR DESCRIPTION
**Pull request by YegorKozlov**
A hackish attempt to fix https://github.com/Adobe-Consulting-Services/acs-aem-commons/issues/2679

The idea is to use Java Reflection API to create a dynamic proxy implementing `com.day.cq.replication.Replicator`

### CODE REVIEW

**Review by davidjgonzalez — APPROVED** [review]
AFIAK this is the only way to work around this other than getting the product team to allow implementations of the interface. Injecting the RQ is its own can of worms :) ... but i dont think we'll solve that without some significant re-thinking of this tool.

**Comment by royteeuwen** [comment]
@davidjgonzalez  is this something you can request, to change this at product team side? Because for me this is the same issue as having your own SlingHttpServletRequest implementation. We should be able to provide this, and not have to hack it by just implementing HttpServletRequest instead of SlingHttpServletRequest. The "feature" of not being able to implement ProviderType's is not a great feature

**Comment by davidjgonzalez** [comment]
@royteeuwen ill make the request - but I would not get your hopes up. :T 

For SlingHttpServletRequest we might have to start requiring/shipping with Sling Servlet Helpers [1] which does alot of the work of supporting synthetic/internal HTTP Requests (which is often the use case with implementing SlingHttpServletRequest) ... also, [1] is included OOTB In AEM CS last time i checked (though dont think its in 6.5, but havent checked lately)

[1] https://sling.apache.org/documentation/bundles/servlet-helpers.html

**Comment by cziegeler** [comment]
Do you really want to have code in a common library that relies on implementation details? I can only suggest to not do this. Reflection, setting private fields are no-gos! If you want to achieve something that is not possible with the API today, start the conversation to enhance the API - but do not hack around it
Please also note that once you go this route and implement Replicator (a provider type which you shouldn't implement), then your code will break with every update to that interface. That's one of the reasons why the check exists in the first place

**Comment by YegorKozlov** [comment]
> Do you really want to have code in a common library that relies on implementation details? I can only suggest to not do this. Reflection, setting private fields are no-gos! If you want to achieve something that is not possible with the API today, start the conversation to enhance the API - but do not hack around it
> Please also note that once you go this route and implement Replicator (a provider type which you shouldn't implement), then your code will break with every update to that interface. That's one of the reasons why the check exists in the first place

I agree that using reflection smells. You can consider it as a short-term fix only. 
Extending the WCM API, to which PageManager belongs, may take months or even years and we need to balance between "making it work" and "doing it right".  Even if we extend the API, it will only be available on new versions of AEM .

**Pull request merged**
