### PR TITLE
Cleanups: Fix broken paint connections in Version Compare

### PR DESCRIPTION
**Pull request by reggie7**
Fix for [1835](https://github.com/Adobe-Consulting-Services/acs-aem-commons/issues/1835). Actually the fix is within frontend files. Java cleanup is a side-effect, it turned out that the BE output was enough already. But I'm leaving those in as e.g. code duplication was reduced, etc.

### CODE REVIEW

**Comment by davidjgonzalez** [comment]
@reggie7 thanks for fixing! This PR's changes are really hard to review; Any ideas how/why this might be happening? If not, I'll take your word it's fully functional, as trying to truly grok what's changed/how is pretty hard. :)

**Comment by kwin** [comment]
I guess this is due to some IDE autoformatting. Can we get a cleaner version of a diff somehow?

**Comment by reggie7** [comment]
@davidjgonzalez well yeah, true, I've made some refactors in BE that after all do not affect the solution so much. In the first attempt I needed them, but then a much simpler FE-only approach was enough. Though following the [boy scout rule](https://deviq.com/boy-scout-rule/) - I've left those BE adjustments in place anyway. The gist is in the non-`java` files.
There's an option to split this PR into smaller chunks or drop the refactor, if needed.

**Comment by reggie7** [comment]
[1933](https://github.com/Adobe-Consulting-Services/acs-aem-commons/pull/1933) has the fix, let's first focus on the other one, then this one will cover only the refactors.

**Pull request closed without merging**
