### PR TITLE
Addressing issue 1498

### PR DESCRIPTION
**Pull request by heervisscher**
Removing config files

### CODE REVIEW

**Comment by heervisscher** [comment]
done

**Comment by badvision** [comment]
Good hussle guys!!

**Comment by davidjgonzalez** [comment]
Look at that - we got en entire release sorted before @badvision even rolled outta bed ;)

**Comment by badvision** [comment]
;P

**Comment by ajaykpaul** [comment]
As of today with latest ACS commons release and AEM 6.5 with SP2, this one is still a valid bug.

**Comment by rbotha78** [comment]
It's working correctly on my local 6.5.2 with ACS commons 4.4.0

**Pull request merged**
