### PR TITLE
Issue #1539 replace encapsulated usage of QB with CloseableQB.

### PR DESCRIPTION
**Pull request by adamcin**
See #1686 for background. 

TODO:

evaluate content/src/main/content/jcr_root/apps/acs-commons/granite/ui/components/form/queryautocomplete/datasource/datasource.jsp for similar treatment.

### CODE REVIEW

**Comment by badvision** [comment]
I like where this is headed.  Couldn't Query implement Closeable and therefore allow us to use try-with-resources (autoclose)?

**Comment by adamcin** [comment]
@badvision Adobe could fix the issue in a deeper way that wouldn't require closing the Hit ResourceResolver, but only if it changed the QueryBuilder API to accept the original ResourceResolver in the first place instead of the underlying JCR Session. I added the CloseableQuery interface under the assumption that that kind of API refactoring likely won't happen quickly.

**Comment by badvision** [comment]
Sure but I noticed a lot of cases where the results are used within a try/catch anyway, so using Closable might tidy things up a little bit.

**Comment by adamcin** [comment]
@badvision Yes, in some cases, a type may not have access to a `@Reference QueryBuilder`, like `OnDeployScriptBase`, where instead the QueryBuilder is retrievable only by using `ResourceResolver.adaptTo(QueryBuilder.class)`. I didn't want to go so far as to implement an AdapterFactory just for this situation, because I don't like that pattern for retrieving a QueryBuilder to begin with (nothing about the ResourceResolver being adapted has anything to do with the QueryBuilder being returned). 

The other case is the `QueryBuilderViewQuery`, which accepts a query in its constructor. Since the type is provided in a constructor, I can't create it in a try-with-resources block with in the execute method without changing a bunch of other logic outside the class. It's easier just to use try/finally block and close the query explicitly.

**Comment by badvision** [comment]
Well it's your option to take it further or leave as-is.  I think it's a step in a great direction either way.

**Comment by badvision** [comment]
Nice.  👍 from me.  @justinedelson any thoughts on this one?

**Pull request merged**
