### PR TITLE
remove java8 specific javadoc-parameters from analysis profile

### PR DESCRIPTION
**Pull request by joerghoh**
Fixing #605 
Now the analysis profile should work with java7 again.

### CODE REVIEW

**Comment by bstopp** [comment]
Great name for the profile.

**Comment by justinedelson** [comment]
Hmmm. JDK 7 has been EOL for 8 months. can't we just switch the minimum JDK version to 1.8?

**Comment by bstopp** [comment]
There are still a large number of companies which haven't shifted over to JDK 8, even with the EOL out there, for whatever reason.

**Comment by justinedelson** [comment]
in d77cd77, I implemented a different solution which solves the same problem but without requiring the inclusion of a different profile on the command line.

**Comment by joerghoh** [comment]
@justinedelson I don't really see the huge difference here ... My patch did not require to provide a profile on the command line, but rather activated the profile when you're running on java 8. Pretty much the same as your patch does.

**Comment by justinedelson** [comment]
sorry - my bad. I misread your PR. I guess the change is identical, except for the formatting :)

**Pull request closed without merging**
