### PR TITLE
Feature/run prs with readwrite token

### PR DESCRIPTION
**Pull request by davidjgonzalez**

### CODE REVIEW

**Comment by kwin** [comment]
@davidjgonzalez Why did you have to revert https://github.com/Adobe-Consulting-Services/acs-aem-commons/pull/2654 in the first place? (https://github.com/Adobe-Consulting-Services/acs-aem-commons/commit/14fac98075230b83fa9dbebb156520f869fe01af). What is different in this PR?

**Comment by davidjgonzalez** [comment]
Nothing is different - i merged #2654 to master, then updated my branch (thinking it would fix my build issue) - but it just stalled my branch's build out, so i reverted it from master since it didnt seem to be working.

**Comment by davidjgonzalez** [comment]
This was the PR .. 

https://github.com/Adobe-Consulting-Services/acs-aem-commons/pull/2667

We can merge it in again to master if we want; I just don't know that PR's based on it will ever finish collecting status. I wanted to try to cut 5.0.8 tonight (and merge/re-run build across the open PR's takes so long - wanted to get a jump on it while i was working -- since updating w/ latest while time-consuming, is usually mindless :)

WDYT? Merge to master for now - and admin merge PR's if we need?

**Review by kwin — DISMISSED** [review]

**Comment by davidjgonzalez** [comment]
@kwin ah - i thought they might be related due to:  https://github.com/ScaCap/action-surefire-report/issues/31
It looked like your PR addressed the issue w/ permissions of PR's from forks (which appears to be the issue here).

Either way - this issue's change seems to cause any build that included it to get stuck with: 

2021-08-25 at 11 50 AM

I assume this is not expected behavior?

**Comment by kwin** [comment]
The current yaml has one issue:

GH reports Invalid workflow file
The workflow is not valid. .github/workflows/maven.yml (Line: 50, Col: 11): A mapping was not expected

**Comment by davidjgonzalez** [comment]
ah - ok - that explains the stuck build status (btw, where do you see that output? ... havent spent enough time w GA's :( )

**Review by kwin — APPROVED** [review]

**Pull request merged**
