### PR TITLE
Fix/2869 - Error page handler support 500s on AEM CS

### PR DESCRIPTION
**Pull request by davidjgonzalez**

### CODE REVIEW

**Review by kwin — CHANGES_REQUESTED** [review]
@davidjgonzalez It looks like there is too many commits on this PR, some seem to refer to #2712

**Comment by davidjgonzalez** [comment]
@kwin - yeh, just realized i didnt reset upstream from yegor before doing this, one sec - let me fix

**Comment by davidjgonzalez** [comment]
OK - should be better now

**Review by kwin — APPROVED** [review]
LGTM

**Pull request merged**
