### PR TITLE
JDK11 support

### PR DESCRIPTION
**Pull request by davidjgonzalez**
testing..

### CODE REVIEW

**Comment by davidjgonzalez** [comment]
[ERROR] Failures: 
[ERROR]   RemoteAssetsNodeSyncImplTest.testSync:219->validateSyncAssets:296 expected:<[mix:referenceable, mix:versionable]> but was:<null>
[ERROR] Errors: 
[ERROR]   FileAssetIngestorTest.testSftpRecursion:316->getSftpChannelMock:394 » IllegalAccess
[ERROR]   FileOrRenditionTest.testSftpSourceGetLength:118 » NoClassDefFound Could not in...
[ERROR]   FileOrRenditionTest.testSftpSourceGetStream:146 » NoClassDefFound Could not in...
[ERROR]   VersionServiceImplTest.lastVersion_error_returnNull:106 Mockito 
Checked excep...
[ERROR]   VersionServiceImplTest.lastVersion_listOfVersion_returnLast:96 » ClassCast org...
[ERROR]   VersionServiceImplTest.lastVersion_noElement_returnNull:76 » ClassCast org.moc...
[ERROR]   VersionServiceImplTest.lastVersion_oneVersion_returnVersion:61 » ClassCast org...
[ERROR]   JUnit4Provider.invoke:159->executeTestSet:238->executeWithRerun:273->execute:365 » NoSuchMethod
[ERROR]   JUnit4Provider.invoke:159->executeTestSet:238->executeWithRerun:273->execute:365 » NoSuchMethod
[ERROR]   JUnit4Provider.invoke:159->executeTestSet:238->executeWithRerun:273->execute:365 » NoSuchMethod
[ERROR]   JUnit4Provider.invoke:159->executeTestSet:238->executeWithRerun:273->execute:365 » NoSuchMethod
[ERROR]   JUnit4Provider.invoke:159->executeTestSet:238->executeWithRerun:273->execute:365 » NoSuchMethod
[ERROR]   JUnit4Provider.invoke:159->executeTestSet:238->executeWithRerun:273->execute:365 » NoSuchMethod
[ERROR]   JUnit4Provider.invoke:159->executeTestSet:238->executeWithRerun:273->execute:365 » NoSuchMethod
[ERROR]   JUnit4Provider.invoke:159->executeTestSet:238->executeWithRerun:273->execute:365 » NoSuchMethod
[ERROR]   JUnit4Provider.invoke:159->executeTestSet:238->executeWithRerun:273->execute:365 » NoSuchMethod
[ERROR]   JUnit4Provider.invoke:159->executeTestSet:238->executeWithRerun:273->execute:365 » NoSuchMethod
[ERROR]   JUnit4Provider.invoke:159->executeTestSet:238->executeWithRerun:273->execute:365 » NoSuchMethod
[ERROR]   JUnit4Provider.invoke:159->executeTestSet:238->executeWithRerun:273->execute:365 » NoSuchMethod
[ERROR]   JUnit4Provider.invoke:159->executeTestSet:238->executeWithRerun:273->execute:365 » NoSuchMethod
[ERROR]   JUnit4Provider.invoke:159->executeTestSet:238->executeWithRerun:273->execute:365 » NoSuchMethod
[ERROR]   JUnit4Provider.invoke:159->executeTestSet:238->executeWithRerun:273->execute:365 » NoSuchMethod
[ERROR]   JUnit4Provider.invoke:159->executeTestSet:238->executeWithRerun:273->execute:365 » NoSuchMethod
[INFO] 
[ERROR] Tests run: 1380, Failures: 1, Errors: 23, Skipped: 0

**Comment by reggie7** [comment]
Hey, let me maybe reply to [1940](https://github.com/Adobe-Consulting-Services/acs-aem-commons/pull/1940#issuecomment-500501361) here instead, @davidjgonzalez.

I've checked out your branch locally and merged it with my [collective branch for all the test fixes for `Java 11`](https://github.com/reggie7/acs-aem-commons/tree/fix-java-11), the result being [fix-java-11+jdk11](https://github.com/reggie7/acs-aem-commons/tree/fix-java-11%2Bjdk11) and the result are these test failures (on both `8` & `11`):

```
[ERROR] Failures:
[ERROR]   RemoteAssetsNodeSyncImplTest.testSync:219->validateSyncAssets:296 expected:<[mix:referenceable, mix:versionable]> but was:<null>
[ERROR] Errors:
[ERROR]   AllEntryNodesCountVisitorTest.unnecessary Mockito stubbings » UnnecessaryStubbing
[ERROR]   EntryNodeByStringKeyVisitorTest.unnecessary Mockito stubbings » UnnecessaryStubbing
[ERROR]   EntryNodeMapVisitorTest.unnecessary Mockito stubbings » UnnecessaryStubbing
U...
[ERROR]   ExpiredNodesVisitorTest.unnecessary Mockito stubbings » UnnecessaryStubbing
U...
[ERROR]   InvalidateAllNodesVisitorTest.unnecessary Mockito stubbings » UnnecessaryStubbing
[ERROR]   TotalCacheSizeVisitorTest.unnecessary Mockito stubbings » UnnecessaryStubbing ...
[ERROR]   RenovatorTest.unnecessary Mockito stubbings » UnnecessaryStubbing
Unnecessary...
[ERROR]   PageCompareDataLoaderImplTest.unnecessary Mockito stubbings » UnnecessaryStubbing
[ERROR]   VersionServiceImplTest.lastVersion_error_returnNull:111 Mockito
Checked excep...
[ERROR]   VersionServiceImplTest.lastVersion_listOfVersion_returnLast:101 » NullPointer
[ERROR]   VersionServiceImplTest.lastVersion_noElement_returnNull:81 » NullPointer
[ERROR]   VersionServiceImplTest.lastVersion_oneVersion_returnVersion:66 » NullPointer
[ERROR]   FileImporterTest.testIOException »  Unexpected exception, expected<com.day.cq....
[ERROR]   JUnit4Provider.invoke:159->executeTestSet:238->executeWithRerun:273->execute:365 » NoSuchMethod
[ERROR]   JUnit4Provider.invoke:159->executeTestSet:238->executeWithRerun:273->execute:365 » NoSuchMethod
[ERROR]   JUnit4Provider.invoke:159->executeTestSet:238->executeWithRerun:273->execute:365 » NoSuchMethod
[ERROR]   JUnit4Provider.invoke:159->executeTestSet:238->executeWithRerun:273->execute:365 » NoSuchMethod
[ERROR]   JUnit4Provider.invoke:159->executeTestSet:238->executeWithRerun:273->execute:365 » NoSuchMethod
[ERROR]   JUnit4Provider.invoke:159->executeTestSet:238->executeWithRerun:273->execute:365 » NoSuchMethod
[ERROR]   JUnit4Provider.invoke:159->executeTestSet:238->executeWithRerun:273->execute:365 » NoSuchMethod
[ERROR]   JUnit4Provider.invoke:159->executeTestSet:238->executeWithRerun:273->execute:365 » NoSuchMethod
[INFO]
[ERROR] Tests run: 1404, Failures: 1, Errors: 21, Skipped: 0
```

On my branch [fix-java-11](https://github.com/reggie7/acs-aem-commons/tree/fix-java-11) the test failures are the following:

```
[ERROR] Errors:
[ERROR]   JCRHttpCacheStoreImplTest.initializationError » Objenesis java.lang.reflect.In...
[ERROR]   InvalidateByCacheConfigVisitorTest.initializationError » Objenesis java.lang.r...
[ERROR]   EntryNodeWriterTest.initializationError » Objenesis java.lang.reflect.Invocati...
[ERROR]   I18nProviderImplTest.initializationError » Objenesis java.lang.reflect.Invocat...
[ERROR]   RemoteAssetDecoratorTest.initializationError » Objenesis java.lang.reflect.Inv...
[ERROR]   MultiFieldPanelWCMUseTest.initializationError » Objenesis java.lang.reflect.In...
[ERROR]   WorkflowPackageManagerImplTest.initializationError » Objenesis java.lang.refle...
[ERROR]   BrandPortalSyncProcessTest.initializationError » Objenesis java.lang.reflect.I...
[INFO]
[ERROR] Tests run: 1396, Failures: 0, Errors: 8, Skipped: 0
```

When I've run [feature/jdk11](https://github.com/davidjgonzalez/acs-aem-commons/tree/feature/jdk11), the results were as follows:
```[ERROR] Failures:
[ERROR]   RemoteAssetsNodeSyncImplTest.testSync:219->validateSyncAssets:296 expected:<[mix:referenceable, mix:versionable]> but was:<null>
[ERROR] Errors:
[ERROR]   IntegrationServiceImplTest.testJwtToken:77 » NoClassDefFound javax/xml/bind/Da...
[ERROR]   S3AssetIngestorTest.testCreateFolders:292 » NoClassDefFound javax/xml/bind/Dat...
[ERROR]   S3AssetIngestorTest.testCreateFoldersWithBasePath:315 » NoClassDefFound javax/...
[ERROR]   S3AssetIngestorTest.testCreateFoldersWithHyphens:339 » NoClassDefFound javax/x...
[ERROR]   S3AssetIngestorTest.testImportAssets:188 » NoClassDefFound javax/xml/bind/Data...
[ERROR]   S3AssetIngestorTest.testImportAssetsToExistingRootFolder:245 » NoClassDefFound
[ERROR]   S3AssetIngestorTest.testImportAssetsToNewRootFolder:221 » NoClassDefFound java...
[ERROR]   S3AssetIngestorTest.testImportAssetsWithBasePath:268 » NoClassDefFound javax/x...
[ERROR]   S3AssetIngestorTest.testImportAssetsWithBucketContainingJustFolders:170 » NoClassDefFound
[ERROR]   S3AssetIngestorTest.testImportAssetsWithException »  Unexpected exception, exp...
[ERROR]   RemoteAssetsBinarySyncImplTest.testSycnAssetFailureDueToOriginalRenditionNotFound:236->setupFinish:148 » NoClassDefFound
[ERROR]   RemoteAssetsBinarySyncImplTest.testSycnAssetFailureDueToRenditionError:216->setupFinish:148 » NoClassDefFound
[ERROR]   RemoteAssetsBinarySyncImplTest.testSycnAssetFailureLogsErrorIfAssetCannotBeFlaggedAsFailed:256->setupFinish:148 » NoClassDefFound
[ERROR]   RemoteAssetsBinarySyncImplTest.testSycnAssetSuccessWithRemovalOfNotFoundRendition:197->setupFinish:148 » NoClassDefFound
[ERROR]   RemoteAssetsBinarySyncImplTest.testSyncAssetSuccess:178->setupFinish:148 » NoClassDefFound
[ERROR]   PageCompareDataImplTest.getLines:143->mockResource:216 ClassCast class org.moc...
[ERROR]   PageCompareDataImplTest.getPath:118->mockResource:216 ClassCast class org.mock...
[ERROR]   PageCompareDataImplTest.getRecursiveLines:164->mockResource:216 ClassCast clas...
[ERROR]   PageCompareDataImplTest.getResource_shouldReturnValue:78->mockResource:216 ClassCast
[ERROR]   PageCompareDataImplTest.getVersion:92->mockResource:216 ClassCast class org.mo...
[ERROR]   PageCompareDataImplTest.getVersionDate:105->mockResource:216 ClassCast class o...
[ERROR]   PageCompareDataImplTest.getVersions:130->mockResource:216 ClassCast class org....
[ERROR]   PageCompareDataImplTest.shouldInitialize:66->mockResource:216 ClassCast class ...
[ERROR]   PageCompareDataLoaderImplTest.shouldInitialize:40 » ClassCast class org.mockit...
[ERROR]   PropertiesTest.lastModified_hasProperty_Date:48 ClassCast class org.mockito.co...
[ERROR]   VersionServiceImplTest.lastVersion_error_returnNull:106 Mockito
Checked excep...
[ERROR]   VersionServiceImplTest.lastVersion_listOfVersion_returnLast:93->mockResource:120 ClassCast
[ERROR]   VersionServiceImplTest.lastVersion_noElement_returnNull:73->mockResource:120 ClassCast
[ERROR]   VersionServiceImplTest.lastVersion_oneVersion_returnVersion:58->mockResource:120 ClassCast
[ERROR]   FileImporterTest.setup:71 » IllegalArgument javax.jcr.RepositoryFactory is not...
[ERROR]   FileImporterTest.setup:71 » IllegalArgument javax.jcr.RepositoryFactory is not...
[ERROR]   FileImporterTest.setup:71 » IllegalArgument javax.jcr.RepositoryFactory is not...
[ERROR]   FileImporterTest.setup:71 » IllegalArgument javax.jcr.RepositoryFactory is not...
[ERROR]   FileImporterTest.setup:71 » IllegalArgument javax.jcr.RepositoryFactory is not...
[ERROR]   FileImporterTest.setup:71 » IllegalArgument javax.jcr.RepositoryFactory is not...
[ERROR]   FileImporterTest.setup:71 » IllegalArgument javax.jcr.RepositoryFactory is not...
[ERROR]   FileImporterTest.setup:71 » IllegalArgument javax.jcr.RepositoryFactory is not...
[ERROR]   JUnit4Provider.invoke:159->executeTestSet:238->executeWithRerun:273->execute:365 » NoSuchMethod
[ERROR]   JUnit4Provider.invoke:159->executeTestSet:238->executeWithRerun:273->execute:365 » NoSuchMethod
[ERROR]   JUnit4Provider.invoke:159->executeTestSet:238->executeWithRerun:273->execute:365 » NoSuchMethod
[ERROR]   JUnit4Provider.invoke:159->executeTestSet:238->executeWithRerun:273->execute:365 » NoSuchMethod
[ERROR]   JUnit4Provider.invoke:159->executeTestSet:238->executeWithRerun:273->execute:365 » NoSuchMethod
[ERROR]   JUnit4Provider.invoke:159->executeTestSet:238->executeWithRerun:273->execute:365 » NoSuchMethod
[ERROR]   JUnit4Provider.invoke:159->executeTestSet:238->executeWithRerun:273->execute:365 » NoSuchMethod
[ERROR]   JUnit4Provider.invoke:159->executeTestSet:238->executeWithRerun:273->execute:365 » NoSuchMethod
[ERROR]   JUnit4Provider.invoke:159->executeTestSet:238->executeWithRerun:273->execute:365 » NoSuchMethod
[ERROR]   JUnit4Provider.invoke:159->executeTestSet:238->executeWithRerun:273->execute:365 » NoSuchMethod
[ERROR]   JUnit4Provider.invoke:159->executeTestSet:238->executeWithRerun:273->execute:365 » NoSuchMethod
[ERROR]   JUnit4Provider.invoke:159->executeTestSet:238->executeWithRerun:273->execute:365 » NoSuchMethod
[ERROR]   JUnit4Provider.invoke:159->executeTestSet:238->executeWithRerun:273->execute:365 » NoSuchMethod
[ERROR]   JUnit4Provider.invoke:159->executeTestSet:238->executeWithRerun:273->execute:365 » NoSuchMethod
[ERROR]   JUnit4Provider.invoke:159->executeTestSet:238->executeWithRerun:273->execute:365 » NoSuchMethod
[ERROR]   JUnit4Provider.invoke:159->executeTestSet:238->executeWithRerun:273->execute:365 » NoSuchMethod
[INFO]
[ERROR] Tests run: 1380, Failures: 1, Errors: 53, Skipped: 0
```

What should we do about it all then @davidjgonzalez? There's some progress on both sides, but none is finished yet. What would you suggest? And what is the purpose of closing this PR?

**Comment by davidjgonzalez** [comment]
@reggie7 The results of my branch i posted were on Java8 (dont have j11 installed yet; been putting off finding a good jdk switcher). 

I have no idea why your results are so different.. ?

Anyhow - I just figured I'd throw my branch out there to see if it's useful, especially in that it updates the test dependencies; i was able to make most updates to tests by doing regex find replaces (ex. org.mockito.Matchers.* is now deprecated, and `getElementAt(..)`'s signature has changed slightly.

I closed this because I was using travis to check the J11 builds out (since i dont have j11 installed yet) :) 

The few issues I had left on mine, I didn't have a clear resolution for. 

We can continue with your individual fixes and then update our dependencies later; seemed like a good time to clean them all up though as the updated deps seem to handle some JDK11 issues anyhow.

**Comment by reggie7** [comment]
Yup - and I just confirmed that the 7 issues
```JUnit4Provider.invoke:159->executeTestSet:238->executeWithRerun:273->execute:365 » NoSuchMethod```
from [fix-java-11+jdk11](https://github.com/reggie7/acs-aem-commons/tree/fix-java-11%2Bjdk11) are directly related 1-1 to
```
EntryNodeWriterTest.initializationError » Objenesis java.lang.reflect.Invocati...
I18nProviderImplTest.initializationError » Objenesis java.lang.reflect.Invocat...
RemoteAssetDecoratorTest.initializationError » Objenesis java.lang.reflect.Inv...
MultiFieldPanelWCMUseTest.initializationError » Objenesis java.lang.reflect.In...
WorkflowPackageManagerImplTest.initializationError » Objenesis java.lang.refle...
BrandPortalSyncProcessTest.initializationError » Objenesis java.lang.reflect.I…
JCRHttpCacheStoreImplTest.initializationError » Objenesis java.lang.reflect.In...
```
from [fix-java-11](https://github.com/reggie7/acs-aem-commons/tree/fix-java-11) - so it's like the same actually :(

**Pull request closed without merging**
