### PR TITLE
Fix compilation warnings

### PR DESCRIPTION
**Pull request by joerghoh**
* suppress deprecation warnings because we cannot fix them right now or with the currrent implementation
* use the static method valueOf instead of the constructors of the wrapped primitive types (Java9)
* replace type.newInstance() with the recommended version (Java9)

### CODE REVIEW

**Comment by badvision** [comment]
@joerghoh The two code climate failures are not a result of a change in the code are they?

**Comment by joerghoh** [comment]
Yeah, though about shorter signatures ... but if that is complaining, I will fix it.

**Comment by davidjgonzalez** [comment]
@joerghoh What's the importance of the Java 9 call out? These obviously work in Java8 (travis passes). Did these only become recommendation in Java9?

**Comment by joerghoh** [comment]
I mentioned "java 9" because these deprecations were made with that version, so you don't see it when you only build on Java 8.

**Pull request merged**
