### PR TITLE
Feature/default values for configs

### PR DESCRIPTION
**Pull request by Sc0rpic0m**
Fixes https://github.com/Adobe-Consulting-Services/acs-aem-commons/issues/1652 and https://github.com/Adobe-Consulting-Services/acs-aem-commons/issues/1645 (and many more potential bugs related to this issue)

### CODE REVIEW

**Comment by badvision** [comment]
👍 +1 from me... @joerghoh ?  @davidjgonzalez ?  @justinedelson ?

**Comment by davidjgonzalez** [comment]
As an approach, this looks good - id like to go through each touched file and double-check there aren't any misses, etc. I suppose we should also true this up against the original list of touched files as well to make sure they're all covered.

when dealing w/ this magnitude of change, its just so easy to make a few mistakes/misses; 2nd/3rd pair of eyes would be good.

**Comment by badvision** [comment]
Agreed!  Please chime in folks if you have a moment to look this one over.

**Comment by Sc0rpic0m** [comment]
I went over all the activate methods using the proxy config using this regex search: activate\(([a-zA-Z]*)\.Config    - good luck! I don't have this kind of time anymore to do a list by list compare with the original PR, because now I'm 110% allocated on projects :(

**Comment by joerghoh** [comment]
@Sc0rpic0m @badvision  any chance that we merge this PR to a branch of the acs-aem-commons repo so we can start to make improvements? I would like to rewrite a number of unittests before merging...

**Comment by badvision** [comment]
Done and done.  Thanks for your contributions!!!

**Pull request merged**
