### PR TITLE
Add more granular environment indicator css control

### PR DESCRIPTION
**Pull request by paul-bjorkstrand**
* enables the ability to always include the base CSS (regardless if cssOverride is set)
* enables the ability to always include the background color CSS (regardless if cssOverride is set)
* separates the three components of the CSS into separate style rules, making it easier to use common to all environments override CSS in conjunction with a custom CSS background color
* keeps backwards compatibility intact

### CODE REVIEW

**Comment by paul-bjorkstrand** [comment]
Apologies for the PR with broken tests, but my machine is struggling to run the tests at all (Windows, of course). I'll get the tests fixed up and update

**Comment by paul-bjorkstrand** [comment]
Not sure what is wrong, but something is screwy with the formatter for the test, I'll address that in a new commit.

**Comment by paul-bjorkstrand** [comment]
I am at a loss as to why the Travis build fails. My local is a CentOS VM using JDK8 (1.8.0_201, to be specific) and Maven 3.6.1. Running the two parts of the build (`mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V` and `mvn verify -B`) throws no errors.

I'm wondering if there is something with the JDK itself that might be causing the errors in [the Travis build](https://travis-ci.org/Adobe-Consulting-Services/acs-aem-commons/builds/572911720?utm_source=github_status&utm_medium=notification).

@davidjgonzalez, if you don't mind taking a look, I would appreciate it.

**Comment by badvision** [comment]
There are merge conflicts @klcodanr -- And yeah it's weird that there are CI failures, as they are coming from the bundle.  Hopefully if we merge the latest it will clear up?

**Comment by paul-bjorkstrand** [comment]
Fixed the merge conflicts, but I still don't get why travis fails. I have roughly the same build process running on a centos vm. There is a slight difference between Java versions: travis uses (assuming Oracle JDK) `1.8.0_151-b12`, mine is (OpenJDK) `1.8.0-201-b09`. If that is the problem, I would be surprised.

**Comment by davidjgonzalez** [comment]
@paul-bjorkstrand This PR is touching 72 files - any way you can update the PR to only touch the files required for this chang?

**Comment by paul-bjorkstrand** [comment]
Closing this one, in favor of a new PR: #2174

**Pull request closed without merging**
