### PR TITLE
Fix JDK 11 test errors for Remote Assets and other tests with Mock Server

### PR DESCRIPTION
**Pull request by HitmanInWis**
- Updated RemoteAssetDecoratorTest to no longer rely on PowerMockito

- Updated version of mockserver to fix JDK 11 errors in tests for IntegrationServiceImplTest, S3AssetIngestorTest, and RemoteAssetsBinarySyncImplTest

JDK 11 Before:
```
[ERROR] Errors: 
[ERROR]   IntegrationServiceImplTest.testJwtToken:77 » NoClassDefFound javax/xml/bind/Da...
[ERROR]   PowerMockErrorPageCacheImplTest.initializationError » Objenesis java.lang.refl...
[ERROR]   JCRHttpCacheStoreImplTest.initializationError » Objenesis java.lang.reflect.In...
[ERROR]   I18nProviderImplTest.initializationError » Objenesis java.lang.reflect.Invocat...
[ERROR]   S3AssetIngestorTest.testCreateFolders:292 » NoClassDefFound javax/xml/bind/Dat...
[ERROR]   S3AssetIngestorTest.testCreateFoldersWithBasePath:315 » NoClassDefFound javax/...
[ERROR]   S3AssetIngestorTest.testCreateFoldersWithHyphens:339 » NoClassDefFound javax/x...
[ERROR]   S3AssetIngestorTest.testImportAssets:188 » NoClassDefFound javax/xml/bind/Data...
[ERROR]   S3AssetIngestorTest.testImportAssetsToExistingRootFolder:245 » NoClassDefFound
[ERROR]   S3AssetIngestorTest.testImportAssetsToNewRootFolder:221 » NoClassDefFound java...
[ERROR]   S3AssetIngestorTest.testImportAssetsWithBasePath:268 » NoClassDefFound javax/x...
[ERROR]   S3AssetIngestorTest.testImportAssetsWithBucketContainingJustFolders:170 » NoClassDefFound
[ERROR]   S3AssetIngestorTest.testImportAssetsWithException »  Unexpected exception, exp...
[ERROR]   RemoteAssetsBinarySyncImplTest.testSycnAssetFailureDueToOriginalRenditionNotFound:236->setupFinish:148 » NoClassDefFound
[ERROR]   RemoteAssetsBinarySyncImplTest.testSycnAssetFailureDueToRenditionError:216->setupFinish:148 » NoClassDefFound
[ERROR]   RemoteAssetsBinarySyncImplTest.testSycnAssetFailureLogsErrorIfAssetCannotBeFlaggedAsFailed:256->setupFinish:148 » NoClassDefFound
[ERROR]   RemoteAssetsBinarySyncImplTest.testSycnAssetSuccessWithRemovalOfNotFoundRendition:197->setupFinish:148 » NoClassDefFound
[ERROR]   RemoteAssetsBinarySyncImplTest.testSyncAssetSuccess:178->setupFinish:148 » NoClassDefFound
[ERROR]   FileImporterTest.setup:71 » IllegalArgument javax.jcr.RepositoryFactory is not...
[ERROR]   FileImporterTest.setup:71 » IllegalArgument javax.jcr.RepositoryFactory is not...
[ERROR]   FileImporterTest.setup:71 » IllegalArgument javax.jcr.RepositoryFactory is not...
[ERROR]   FileImporterTest.setup:71 » IllegalArgument javax.jcr.RepositoryFactory is not...
[ERROR]   FileImporterTest.setup:71 » IllegalArgument javax.jcr.RepositoryFactory is not...
[ERROR]   FileImporterTest.setup:71 » IllegalArgument javax.jcr.RepositoryFactory is not...
[ERROR]   FileImporterTest.setup:71 » IllegalArgument javax.jcr.RepositoryFactory is not...
[ERROR]   FileImporterTest.setup:71 » IllegalArgument javax.jcr.RepositoryFactory is not...
[ERROR]   BrandPortalSyncProcessTest.initializationError » Objenesis java.lang.reflect.I...
[INFO] 
[ERROR] Tests run: 1434, Failures: 0, Errors: 27, Skipped: 0
[INFO] 
```

JDK11 After:
```
[ERROR] Errors: 
[ERROR]   PowerMockErrorPageCacheImplTest.initializationError » Objenesis java.lang.refl...
[ERROR]   JCRHttpCacheStoreImplTest.initializationError » Objenesis java.lang.reflect.In...
[ERROR]   I18nProviderImplTest.initializationError » Objenesis java.lang.reflect.Invocat...
[ERROR]   FileImporterTest.setup:71 » IllegalArgument javax.jcr.RepositoryFactory is not...
[ERROR]   FileImporterTest.setup:71 » IllegalArgument javax.jcr.RepositoryFactory is not...
[ERROR]   FileImporterTest.setup:71 » IllegalArgument javax.jcr.RepositoryFactory is not...
[ERROR]   FileImporterTest.setup:71 » IllegalArgument javax.jcr.RepositoryFactory is not...
[ERROR]   FileImporterTest.setup:71 » IllegalArgument javax.jcr.RepositoryFactory is not...
[ERROR]   FileImporterTest.setup:71 » IllegalArgument javax.jcr.RepositoryFactory is not...
[ERROR]   FileImporterTest.setup:71 » IllegalArgument javax.jcr.RepositoryFactory is not...
[ERROR]   FileImporterTest.setup:71 » IllegalArgument javax.jcr.RepositoryFactory is not...
[ERROR]   BrandPortalSyncProcessTest.initializationError » Objenesis java.lang.reflect.I...
[INFO] 
[ERROR] Tests run: 1434, Failures: 0, Errors: 12, Skipped: 0
[INFO] 
```

No new errors, just 15 fixed.  All tests pass on Java 8.

### CODE REVIEW

**Comment by davidjgonzalez** [comment]
@HitmanInWis code changes look good, but all travis builds failed. look like they might have timed out?  Restarting them to see.

**Comment by davidjgonzalez** [comment]
@HitmanInWis hmm - even JDK8 travis builds seem to be failing for this PR.. 🤔 
A quick peek at travis logs seems like it might have something to do w/ mock server?

**Comment by HitmanInWis** [comment]
hrmm not sure what to say, will have to look at it when I get some time...builds just fine for me locally with JDK8, I tested before I pushed it up.

**Comment by HitmanInWis** [comment]
Ok @davidjgonzalez this is fixed.  Forgot that travis build fails when the log gets too large, and the new mockserver version had a new class that had to have its logging tamed :)

**Comment by badvision** [comment]
PowerMockito struggles to work well in JDK9+ in general because the class loader has changed so much that mocking static methods can be a bit finicky.   I was able to get it working in another project (same root cause) by adding this annotation to the top of each affected unit test:
```@PowerMockIgnore({"com.sun.org.apache.xerces.*", "javax.xml.*", "org.xml.*", "org.w3c.*"})```

**Comment by badvision** [comment]
Also might try these dependency versions: ```        <dependency>
            <groupId>org.mockito</groupId>
            <artifactId>mockito-core</artifactId>
            <version>2.28.2</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.powermock</groupId>
            <artifactId>powermock-api-mockito2</artifactId>
            <version>2.0.2</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.powermock</groupId>
            <artifactId>powermock-module-junit4</artifactId>
            <version>2.0.2</version>
            <scope>test</scope>
        </dependency>```

**Comment by HitmanInWis** [comment]
Good to know for cases where we need to continue using PowerMockito.  In this case it was for a single static function call which we encapsulated in an instance function, obviating the need for PowerMockito at the expense of leaving one line of code untested, which seems like an okay tradeoff.

**Comment by badvision** [comment]
Yes, absolutely a better solution in this case.  I'm not sure if there is a better way to inject static method behaviors going forward, which is rather a bummer.  The overall recommendation is not to use static methods and write code that better lends itself to testing, but unfortunately that isn't an option if your code uses static utilities like JcrUtils, etc.

**Pull request merged**
